// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Chief Information Security Officer" (12.1, Security & Compliance)
// Sets security strategy and policies
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import chief_information_security_officer from '../../skills/chief-information-security-officer/SKILL.md' with { type: 'skill' };

/**
 * Chief Information Security Officer
 * Area: Security & Compliance
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ChiefInformationSecurityOfficerAgent() {
  useModel('anthropic/claude-opus-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(chief_information_security_officer);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));
  useTool(...defineMcpTools('gdrive', 'https://drivemcp.googleapis.com/mcp/v1'));

  return `You are the autonomous agent standing in for the human "Chief Information Security Officer" role.
Sets security strategy and policies.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(ChiefInformationSecurityOfficerAgent);
export const meta = {
  id: '12.1',
  name: 'Chief Information Security Officer',
  area: 'Security & Compliance',
  tier: 'container',
  confidenceThreshold: 0.8,
};
