// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Chief Information Security Officer" (12.1, Security & Compliance)
// Sets security strategy and policies
'use agent';

import { useModel, useSandbox, useSkill, useMcpConnection } from '@flue/runtime';
import { local } from '@flue/runtime/node';
import chief_information_security_officer from '../../skills/chief-information-security-officer/SKILL.md';

/**
 * Chief Information Security Officer
 * Area: Security & Compliance
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ChiefInformationSecurityOfficerAgent() {
  useModel('anthropic/claude-opus-4-6');
  useSandbox(local());
  useSkill(chief_information_security_officer);
  useMcpConnection({ name: 'github', url: 'https://mcp.github.com/mcp', optional: true });
  useMcpConnection({ name: 'gdrive', url: 'https://drivemcp.googleapis.com/mcp/v1', optional: true });

  return `You are the autonomous agent standing in for the human "Chief Information Security Officer" role.
Sets security strategy and policies.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
ChiefInformationSecurityOfficerAgent.agentName = 'chief-information-security-officer';
export const meta = {
  id: '12.1',
  name: 'Chief Information Security Officer',
  area: 'Security & Compliance',
  tier: 'container',
  confidenceThreshold: 0.8,
};
