// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Compliance Officer" (12.6, Security & Compliance)
// Ensures regulatory compliance (GDPR, HIPAA)
'use agent';

import { useModel, useSandbox, useSkill, useMcpConnection } from '@flue/runtime';
import { local } from '@flue/runtime/node';
import compliance_officer from '../../skills/compliance-officer/SKILL.md';

/**
 * Compliance Officer
 * Area: Security & Compliance
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ComplianceOfficerAgent() {
  useModel('anthropic/claude-opus-4-6');
  useSandbox(local());
  useSkill(compliance_officer);
  useMcpConnection({ name: 'github', url: 'https://mcp.github.com/mcp', optional: true });
  useMcpConnection({ name: 'gdrive', url: 'https://drivemcp.googleapis.com/mcp/v1', optional: true });

  return `You are the autonomous agent standing in for the human "Compliance Officer" role.
Ensures regulatory compliance (GDPR, HIPAA).
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
ComplianceOfficerAgent.agentName = 'compliance-officer';
export const meta = {
  id: '12.6',
  name: 'Compliance Officer',
  area: 'Security & Compliance',
  tier: 'container',
  confidenceThreshold: 0.7,
};
