// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Compliance Officer" (12.6, Security & Compliance)
// Ensures regulatory compliance (GDPR, HIPAA)
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import compliance_officer from '../../skills/compliance-officer/SKILL.md' with { type: 'skill' };

/**
 * Compliance Officer
 * Area: Security & Compliance
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ComplianceOfficerAgent() {
  useModel('anthropic/claude-opus-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(compliance_officer);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));
  useTool(...defineMcpTools('gdrive', 'https://drivemcp.googleapis.com/mcp/v1'));

  return `You are the autonomous agent standing in for the human "Compliance Officer" role.
Ensures regulatory compliance (GDPR, HIPAA).
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(ComplianceOfficerAgent);
export const meta = {
  id: '12.6',
  name: 'Compliance Officer',
  area: 'Security & Compliance',
  tier: 'container',
  confidenceThreshold: 0.7,
};
