// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Identity & Access Manager" (12.7, Security & Compliance)
// Manages authentication and authorization
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import identity_access_manager from '../../skills/identity-access-manager/SKILL.md' with { type: 'skill' };

/**
 * Identity & Access Manager
 * Area: Security & Compliance
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function IdentityAccessManagerAgent() {
  useModel('anthropic/claude-opus-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(identity_access_manager);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));
  useTool(...defineMcpTools('gdrive', 'https://drivemcp.googleapis.com/mcp/v1'));

  return `You are the autonomous agent standing in for the human "Identity & Access Manager" role.
Manages authentication and authorization.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(IdentityAccessManagerAgent);
export const meta = {
  id: '12.7',
  name: 'Identity & Access Manager',
  area: 'Security & Compliance',
  tier: 'container',
  confidenceThreshold: 0.8,
};
