// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Penetration Tester" (12.4, Security & Compliance)
// Simulates attacks to find vulnerabilities
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import penetration_tester from '../../skills/penetration-tester/SKILL.md' with { type: 'skill' };

/**
 * Penetration Tester
 * Area: Security & Compliance
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function PenetrationTesterAgent() {
  useModel('anthropic/claude-opus-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(penetration_tester);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));
  useTool(...defineMcpTools('gdrive', 'https://drivemcp.googleapis.com/mcp/v1'));

  return `You are the autonomous agent standing in for the human "Penetration Tester" role.
Simulates attacks to find vulnerabilities.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(PenetrationTesterAgent);
export const meta = {
  id: '12.4',
  name: 'Penetration Tester',
  area: 'Security & Compliance',
  tier: 'container',
  confidenceThreshold: 0.7,
};
