// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Security Engineer" (12.2, Security & Compliance)
// Implements security controls and features
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import security_engineer from '../../skills/security-engineer/SKILL.md' with { type: 'skill' };

/**
 * Security Engineer
 * Area: Security & Compliance
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function SecurityEngineerAgent() {
  useModel('anthropic/claude-opus-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(security_engineer);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));
  useTool(...defineMcpTools('gdrive', 'https://drivemcp.googleapis.com/mcp/v1'));

  return `You are the autonomous agent standing in for the human "Security Engineer" role.
Implements security controls and features.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(SecurityEngineerAgent);
export const meta = {
  id: '12.2',
  name: 'Security Engineer',
  area: 'Security & Compliance',
  tier: 'container',
  confidenceThreshold: 0.7,
};
