// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "API/Integration Tester" (11.8, Quality Assurance & Testing)
// Tests APIs and system integrations
'use agent';

import { useModel, useSandbox, useSkill, useMcpConnection } from '@flue/runtime';
import { local } from '@flue/runtime/node';
import api_integration_tester from '../../skills/api-integration-tester/SKILL.md';

/**
 * API/Integration Tester
 * Area: Quality Assurance & Testing
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function APIIntegrationTesterAgent() {
  useModel('cloudflare/@cf/meta/llama-3.3-70b-instruct');
  useSandbox(local());
  useSkill(api_integration_tester);
  useMcpConnection({ name: 'github', url: 'https://mcp.github.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "API/Integration Tester" role.
Tests APIs and system integrations.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
APIIntegrationTesterAgent.agentName = 'api-integration-tester';
export const meta = {
  id: '11.8',
  name: 'API/Integration Tester',
  area: 'Quality Assurance & Testing',
  tier: 'container',
  confidenceThreshold: 0.7,
};
