// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Manual Tester" (11.3, Quality Assurance & Testing)
// Performs exploratory and manual testing
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import manual_tester from '../../skills/manual-tester/SKILL.md' with { type: 'skill' };

/**
 * Manual Tester
 * Area: Quality Assurance & Testing
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ManualTesterAgent() {
  useModel('workers-ai/@cf/meta/llama-3.3-70b-instruct');
  useSandbox(container({ ephemeral: true }));
  useSkill(manual_tester);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));

  return `You are the autonomous agent standing in for the human "Manual Tester" role.
Performs exploratory and manual testing.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(ManualTesterAgent);
export const meta = {
  id: '11.3',
  name: 'Manual Tester',
  area: 'Quality Assurance & Testing',
  tier: 'container',
  confidenceThreshold: 0.7,
};
