// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Mobile QA Specialist" (11.7, Quality Assurance & Testing)
// Tests mobile apps across devices
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import mobile_qa_specialist from '../../skills/mobile-qa-specialist/SKILL.md' with { type: 'skill' };

/**
 * Mobile QA Specialist
 * Area: Quality Assurance & Testing
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function MobileQASpecialistAgent() {
  useModel('workers-ai/@cf/meta/llama-3.3-70b-instruct');
  useSandbox(container({ ephemeral: true }));
  useSkill(mobile_qa_specialist);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));

  return `You are the autonomous agent standing in for the human "Mobile QA Specialist" role.
Tests mobile apps across devices.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(MobileQASpecialistAgent);
export const meta = {
  id: '11.7',
  name: 'Mobile QA Specialist',
  area: 'Quality Assurance & Testing',
  tier: 'container',
  confidenceThreshold: 0.7,
};
