// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "QA Manager" (11.1, Quality Assurance & Testing)
// Leads QA team and test strategy
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import qa_manager from '../../skills/qa-manager/SKILL.md' with { type: 'skill' };

/**
 * QA Manager
 * Area: Quality Assurance & Testing
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function QAManagerAgent() {
  useModel('workers-ai/@cf/meta/llama-3.3-70b-instruct');
  useSandbox(container({ ephemeral: true }));
  useSkill(qa_manager);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));

  return `You are the autonomous agent standing in for the human "QA Manager" role.
Leads QA team and test strategy.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(QAManagerAgent);
export const meta = {
  id: '11.1',
  name: 'QA Manager',
  area: 'Quality Assurance & Testing',
  tier: 'container',
  confidenceThreshold: 0.8,
};
