// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "QA Manager" (11.1, Quality Assurance & Testing)
// Leads QA team and test strategy
'use agent';

import { useModel, useSandbox, useSkill, useMcpConnection } from '@flue/runtime';
import { local } from '@flue/runtime/node';
import qa_manager from '../../skills/qa-manager/SKILL.md';

/**
 * QA Manager
 * Area: Quality Assurance & Testing
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function QAManagerAgent() {
  useModel('cloudflare/@cf/meta/llama-3.3-70b-instruct');
  useSandbox(local());
  useSkill(qa_manager);
  useMcpConnection({ name: 'github', url: 'https://mcp.github.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "QA Manager" role.
Leads QA team and test strategy.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
QAManagerAgent.agentName = 'qa-manager';
export const meta = {
  id: '11.1',
  name: 'QA Manager',
  area: 'Quality Assurance & Testing',
  tier: 'container',
  confidenceThreshold: 0.8,
};
