// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Test Automation Engineer" (11.4, Quality Assurance & Testing)
// Builds automated test frameworks
'use agent';

import { useModel, useSandbox, useSkill, useMcpConnection } from '@flue/runtime';
import { local } from '@flue/runtime/node';
import test_automation_engineer from '../../skills/test-automation-engineer/SKILL.md';

/**
 * Test Automation Engineer
 * Area: Quality Assurance & Testing
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function TestAutomationEngineerAgent() {
  useModel('cloudflare/@cf/meta/llama-3.3-70b-instruct');
  useSandbox(local());
  useSkill(test_automation_engineer);
  useMcpConnection({ name: 'github', url: 'https://mcp.github.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "Test Automation Engineer" role.
Builds automated test frameworks.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
TestAutomationEngineerAgent.agentName = 'test-automation-engineer';
export const meta = {
  id: '11.4',
  name: 'Test Automation Engineer',
  area: 'Quality Assurance & Testing',
  tier: 'container',
  confidenceThreshold: 0.7,
};
