// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "UAT Coordinator" (11.10, Quality Assurance & Testing)
// Facilitates user acceptance testing
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import uat_coordinator from '../../skills/uat-coordinator/SKILL.md' with { type: 'skill' };

/**
 * UAT Coordinator
 * Area: Quality Assurance & Testing
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function UATCoordinatorAgent() {
  useModel('workers-ai/@cf/meta/llama-3.3-70b-instruct');
  useSandbox(container({ ephemeral: true }));
  useSkill(uat_coordinator);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));

  return `You are the autonomous agent standing in for the human "UAT Coordinator" role.
Facilitates user acceptance testing.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(UATCoordinatorAgent);
export const meta = {
  id: '11.10',
  name: 'UAT Coordinator',
  area: 'Quality Assurance & Testing',
  tier: 'container',
  confidenceThreshold: 0.7,
};
