// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "UAT Coordinator" (11.10, Quality Assurance & Testing)
// Facilitates user acceptance testing
'use agent';

import { useModel, useSandbox, useSkill, useMcpConnection } from '@flue/runtime';
import { local } from '@flue/runtime/node';
import uat_coordinator from '../../skills/uat-coordinator/SKILL.md';

/**
 * UAT Coordinator
 * Area: Quality Assurance & Testing
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function UATCoordinatorAgent() {
  useModel('cloudflare/@cf/meta/llama-3.3-70b-instruct');
  useSandbox(local());
  useSkill(uat_coordinator);
  useMcpConnection({ name: 'github', url: 'https://mcp.github.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "UAT Coordinator" role.
Facilitates user acceptance testing.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
UATCoordinatorAgent.agentName = 'uat-coordinator';
export const meta = {
  id: '11.10',
  name: 'UAT Coordinator',
  area: 'Quality Assurance & Testing',
  tier: 'container',
  confidenceThreshold: 0.7,
};
