// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
import { agent as agent_0, meta as meta_0 } from './agents/product-management-strategy/chief-product-officer.ts';
import { agent as agent_1, meta as meta_1 } from './agents/product-management-strategy/product-manager.ts';
import { agent as agent_2, meta as meta_2 } from './agents/product-management-strategy/associate-product-manager.ts';
import { agent as agent_3, meta as meta_3 } from './agents/product-management-strategy/product-owner.ts';
import { agent as agent_4, meta as meta_4 } from './agents/product-management-strategy/product-analyst.ts';
import { agent as agent_5, meta as meta_5 } from './agents/product-management-strategy/competitive-analyst.ts';
import { agent as agent_6, meta as meta_6 } from './agents/product-management-strategy/product-operations.ts';
import { agent as agent_7, meta as meta_7 } from './agents/business-analysis-requirements/lead-business-analyst.ts';
import { agent as agent_8, meta as meta_8 } from './agents/business-analysis-requirements/business-analyst.ts';
import { agent as agent_9, meta as meta_9 } from './agents/business-analysis-requirements/systems-analyst.ts';
import { agent as agent_10, meta as meta_10 } from './agents/business-analysis-requirements/process-analyst.ts';
import { agent as agent_11, meta as meta_11 } from './agents/business-analysis-requirements/domain-expert-sme.ts';
import { agent as agent_12, meta as meta_12 } from './agents/business-analysis-requirements/requirements-engineer.ts';
import { agent as agent_13, meta as meta_13 } from './agents/user-research-experience/ux-research-lead.ts';
import { agent as agent_14, meta as meta_14 } from './agents/user-research-experience/user-researcher.ts';
import { agent as agent_15, meta as meta_15 } from './agents/user-research-experience/behavioral-analyst.ts';
import { agent as agent_16, meta as meta_16 } from './agents/user-research-experience/accessibility-specialist.ts';
import { agent as agent_17, meta as meta_17 } from './agents/user-research-experience/information-architect.ts';
import { agent as agent_18, meta as meta_18 } from './agents/user-research-experience/usability-tester.ts';
import { agent as agent_19, meta as meta_19 } from './agents/design/design-director.ts';
import { agent as agent_20, meta as meta_20 } from './agents/design/ux-designer.ts';
import { agent as agent_21, meta as meta_21 } from './agents/design/ui-designer.ts';
import { agent as agent_22, meta as meta_22 } from './agents/design/interaction-designer.ts';
import { agent as agent_23, meta as meta_23 } from './agents/design/visual-designer.ts';
import { agent as agent_24, meta as meta_24 } from './agents/design/motion-designer.ts';
import { agent as agent_25, meta as meta_25 } from './agents/design/design-system-manager.ts';
import { agent as agent_26, meta as meta_26 } from './agents/design/prototyper.ts';
import { agent as agent_27, meta as meta_27 } from './agents/software-architecture/chief-architect.ts';
import { agent as agent_28, meta as meta_28 } from './agents/software-architecture/solutions-architect.ts';
import { agent as agent_29, meta as meta_29 } from './agents/software-architecture/application-architect.ts';
import { agent as agent_30, meta as meta_30 } from './agents/software-architecture/data-architect.ts';
import { agent as agent_31, meta as meta_31 } from './agents/software-architecture/cloud-architect.ts';
import { agent as agent_32, meta as meta_32 } from './agents/software-architecture/integration-architect.ts';
import { agent as agent_33, meta as meta_33 } from './agents/software-architecture/security-architect.ts';
import { agent as agent_34, meta as meta_34 } from './agents/frontend-development/frontend-lead-principal.ts';
import { agent as agent_35, meta as meta_35 } from './agents/frontend-development/frontend-developer.ts';
import { agent as agent_36, meta as meta_36 } from './agents/frontend-development/javascript-typescript-developer.ts';
import { agent as agent_37, meta as meta_37 } from './agents/frontend-development/css-styling-specialist.ts';
import { agent as agent_38, meta as meta_38 } from './agents/frontend-development/frontend-performance-engineer.ts';
import { agent as agent_39, meta as meta_39 } from './agents/frontend-development/web-accessibility-developer.ts';
import { agent as agent_40, meta as meta_40 } from './agents/frontend-development/frontend-build-engineer.ts';
import { agent as agent_41, meta as meta_41 } from './agents/backend-development/backend-lead-principal.ts';
import { agent as agent_42, meta as meta_42 } from './agents/backend-development/backend-developer.ts';
import { agent as agent_43, meta as meta_43 } from './agents/backend-development/api-developer.ts';
import { agent as agent_44, meta as meta_44 } from './agents/backend-development/database-developer.ts';
import { agent as agent_45, meta as meta_45 } from './agents/backend-development/microservices-developer.ts';
import { agent as agent_46, meta as meta_46 } from './agents/backend-development/backend-performance-engineer.ts';
import { agent as agent_47, meta as meta_47 } from './agents/backend-development/integration-developer.ts';
import { agent as agent_48, meta as meta_48 } from './agents/full-stack-development/full-stack-lead.ts';
import { agent as agent_49, meta as meta_49 } from './agents/full-stack-development/full-stack-developer.ts';
import { agent as agent_50, meta as meta_50 } from './agents/full-stack-development/mean-mern-stack-developer.ts';
import { agent as agent_51, meta as meta_51 } from './agents/full-stack-development/rapid-prototyper.ts';
import { agent as agent_52, meta as meta_52 } from './agents/mobile-development/mobile-lead.ts';
import { agent as agent_53, meta as meta_53 } from './agents/mobile-development/ios-developer.ts';
import { agent as agent_54, meta as meta_54 } from './agents/mobile-development/android-developer.ts';
import { agent as agent_55, meta as meta_55 } from './agents/mobile-development/react-native-developer.ts';
import { agent as agent_56, meta as meta_56 } from './agents/mobile-development/flutter-developer.ts';
import { agent as agent_57, meta as meta_57 } from './agents/mobile-development/mobile-ui-ux-developer.ts';
import { agent as agent_58, meta as meta_58 } from './agents/mobile-development/mobile-devops-engineer.ts';
import { agent as agent_59, meta as meta_59 } from './agents/devops-infrastructure/devops-manager.ts';
import { agent as agent_60, meta as meta_60 } from './agents/devops-infrastructure/devops-engineer.ts';
import { agent as agent_61, meta as meta_61 } from './agents/devops-infrastructure/site-reliability-engineer-sre.ts';
import { agent as agent_62, meta as meta_62 } from './agents/devops-infrastructure/cloud-engineer.ts';
import { agent as agent_63, meta as meta_63 } from './agents/devops-infrastructure/platform-engineer.ts';
import { agent as agent_64, meta as meta_64 } from './agents/devops-infrastructure/release-manager.ts';
import { agent as agent_65, meta as meta_65 } from './agents/devops-infrastructure/infrastructure-engineer.ts';
import { agent as agent_66, meta as meta_66 } from './agents/devops-infrastructure/ci-cd-engineer.ts';
import { agent as agent_67, meta as meta_67 } from './agents/devops-infrastructure/configuration-manager.ts';
import { agent as agent_68, meta as meta_68 } from './agents/devops-infrastructure/monitoring-observability-engineer.ts';
import { agent as agent_69, meta as meta_69 } from './agents/quality-assurance-testing/qa-manager.ts';
import { agent as agent_70, meta as meta_70 } from './agents/quality-assurance-testing/qa-engineer.ts';
import { agent as agent_71, meta as meta_71 } from './agents/quality-assurance-testing/manual-tester.ts';
import { agent as agent_72, meta as meta_72 } from './agents/quality-assurance-testing/test-automation-engineer.ts';
import { agent as agent_73, meta as meta_73 } from './agents/quality-assurance-testing/performance-tester.ts';
import { agent as agent_74, meta as meta_74 } from './agents/quality-assurance-testing/security-tester.ts';
import { agent as agent_75, meta as meta_75 } from './agents/quality-assurance-testing/mobile-qa-specialist.ts';
import { agent as agent_76, meta as meta_76 } from './agents/quality-assurance-testing/api-integration-tester.ts';
import { agent as agent_77, meta as meta_77 } from './agents/quality-assurance-testing/regression-tester.ts';
import { agent as agent_78, meta as meta_78 } from './agents/quality-assurance-testing/uat-coordinator.ts';
import { agent as agent_79, meta as meta_79 } from './agents/security-compliance/chief-information-security-officer.ts';
import { agent as agent_80, meta as meta_80 } from './agents/security-compliance/security-engineer.ts';
import { agent as agent_81, meta as meta_81 } from './agents/security-compliance/application-security-engineer.ts';
import { agent as agent_82, meta as meta_82 } from './agents/security-compliance/penetration-tester.ts';
import { agent as agent_83, meta as meta_83 } from './agents/security-compliance/security-analyst.ts';
import { agent as agent_84, meta as meta_84 } from './agents/security-compliance/compliance-officer.ts';
import { agent as agent_85, meta as meta_85 } from './agents/security-compliance/identity-access-manager.ts';
import { agent as agent_86, meta as meta_86 } from './agents/security-compliance/security-operations-analyst.ts';
import { agent as agent_87, meta as meta_87 } from './agents/data-engineering-analytics/data-engineering-manager.ts';
import { agent as agent_88, meta as meta_88 } from './agents/data-engineering-analytics/data-engineer.ts';
import { agent as agent_89, meta as meta_89 } from './agents/data-engineering-analytics/data-warehouse-engineer.ts';
import { agent as agent_90, meta as meta_90 } from './agents/data-engineering-analytics/etl-developer.ts';
import { agent as agent_91, meta as meta_91 } from './agents/data-engineering-analytics/data-analyst.ts';
import { agent as agent_92, meta as meta_92 } from './agents/data-engineering-analytics/business-intelligence-developer.ts';
import { agent as agent_93, meta as meta_93 } from './agents/data-engineering-analytics/data-scientist.ts';
import { agent as agent_94, meta as meta_94 } from './agents/data-engineering-analytics/ml-engineer.ts';
import { agent as agent_95, meta as meta_95 } from './agents/data-engineering-analytics/analytics-engineer.ts';
import { agent as agent_96, meta as meta_96 } from './agents/documentation-technical-writing/documentation-manager.ts';
import { agent as agent_97, meta as meta_97 } from './agents/documentation-technical-writing/technical-writer.ts';
import { agent as agent_98, meta as meta_98 } from './agents/documentation-technical-writing/api-documentation-specialist.ts';
import { agent as agent_99, meta as meta_99 } from './agents/documentation-technical-writing/knowledge-base-manager.ts';
import { agent as agent_100, meta as meta_100 } from './agents/documentation-technical-writing/video-tutorial-creator.ts';
import { agent as agent_101, meta as meta_101 } from './agents/documentation-technical-writing/information-developer.ts';
import { agent as agent_102, meta as meta_102 } from './agents/documentation-technical-writing/content-strategist.ts';
import { agent as agent_103, meta as meta_103 } from './agents/project-management/program-manager.ts';
import { agent as agent_104, meta as meta_104 } from './agents/project-management/project-manager.ts';
import { agent as agent_105, meta as meta_105 } from './agents/project-management/technical-project-manager.ts';
import { agent as agent_106, meta as meta_106 } from './agents/project-management/delivery-manager.ts';
import { agent as agent_107, meta as meta_107 } from './agents/project-management/resource-manager.ts';
import { agent as agent_108, meta as meta_108 } from './agents/project-management/pmo-analyst.ts';
import { agent as agent_109, meta as meta_109 } from './agents/project-management/portfolio-manager.ts';
import { agent as agent_110, meta as meta_110 } from './agents/agile-scrum/agile-coach.ts';
import { agent as agent_111, meta as meta_111 } from './agents/agile-scrum/scrum-master.ts';
import { agent as agent_112, meta as meta_112 } from './agents/agile-scrum/kanban-lead.ts';
import { agent as agent_113, meta as meta_113 } from './agents/agile-scrum/release-train-engineer.ts';
import { agent as agent_114, meta as meta_114 } from './agents/agile-scrum/agile-transformation-lead.ts';
import { agent as agent_115, meta as meta_115 } from './agents/marketing/chief-marketing-officer.ts';
import { agent as agent_116, meta as meta_116 } from './agents/marketing/product-marketing-manager.ts';
import { agent as agent_117, meta as meta_117 } from './agents/marketing/content-marketing-manager.ts';
import { agent as agent_118, meta as meta_118 } from './agents/marketing/digital-marketing-specialist.ts';
import { agent as agent_119, meta as meta_119 } from './agents/marketing/growth-marketer.ts';
import { agent as agent_120, meta as meta_120 } from './agents/marketing/email-marketing-specialist.ts';
import { agent as agent_121, meta as meta_121 } from './agents/marketing/marketing-analyst.ts';
import { agent as agent_122, meta as meta_122 } from './agents/marketing/brand-manager.ts';
import { agent as agent_123, meta as meta_123 } from './agents/marketing/event-marketing-manager.ts';
import { agent as agent_124, meta as meta_124 } from './agents/marketing/partner-marketing-manager.ts';
import { agent as agent_125, meta as meta_125 } from './agents/sales/vp-of-sales.ts';
import { agent as agent_126, meta as meta_126 } from './agents/sales/sales-development-rep-sdr.ts';
import { agent as agent_127, meta as meta_127 } from './agents/sales/account-executive.ts';
import { agent as agent_128, meta as meta_128 } from './agents/sales/enterprise-sales-rep.ts';
import { agent as agent_129, meta as meta_129 } from './agents/sales/solutions-engineer-sales-engineer.ts';
import { agent as agent_130, meta as meta_130 } from './agents/sales/customer-success-manager.ts';
import { agent as agent_131, meta as meta_131 } from './agents/sales/account-manager.ts';
import { agent as agent_132, meta as meta_132 } from './agents/sales/sales-operations-analyst.ts';
import { agent as agent_133, meta as meta_133 } from './agents/sales/revenue-operations-manager.ts';
import { agent as agent_134, meta as meta_134 } from './agents/customer-support/head-of-support.ts';
import { agent as agent_135, meta as meta_135 } from './agents/customer-support/customer-support-rep-tier-1.ts';
import { agent as agent_136, meta as meta_136 } from './agents/customer-support/technical-support-engineer-tier-2.ts';
import { agent as agent_137, meta as meta_137 } from './agents/customer-support/senior-support-engineer-tier-3.ts';
import { agent as agent_138, meta as meta_138 } from './agents/customer-support/support-operations-manager.ts';
import { agent as agent_139, meta as meta_139 } from './agents/customer-support/community-manager.ts';
import { agent as agent_140, meta as meta_140 } from './agents/customer-support/customer-advocate.ts';
import { agent as agent_141, meta as meta_141 } from './agents/customer-support/onboarding-specialist.ts';
import { agent as agent_142, meta as meta_142 } from './agents/customer-support/training-specialist.ts';
import { agent as agent_143, meta as meta_143 } from './agents/legal-compliance/general-counsel.ts';
import { agent as agent_144, meta as meta_144 } from './agents/legal-compliance/corporate-lawyer.ts';
import { agent as agent_145, meta as meta_145 } from './agents/legal-compliance/privacy-officer.ts';
import { agent as agent_146, meta as meta_146 } from './agents/legal-compliance/intellectual-property-attorney.ts';
import { agent as agent_147, meta as meta_147 } from './agents/legal-compliance/compliance-manager.ts';
import { agent as agent_148, meta as meta_148 } from './agents/legal-compliance/contract-manager.ts';
import { agent as agent_149, meta as meta_149 } from './agents/legal-compliance/paralegal.ts';

export const AGENT_REGISTRY = {
  '1.1': { agent: agent_0, meta: meta_0 },
  '1.2': { agent: agent_1, meta: meta_1 },
  '1.3': { agent: agent_2, meta: meta_2 },
  '1.4': { agent: agent_3, meta: meta_3 },
  '1.5': { agent: agent_4, meta: meta_4 },
  '1.6': { agent: agent_5, meta: meta_5 },
  '1.7': { agent: agent_6, meta: meta_6 },
  '2.1': { agent: agent_7, meta: meta_7 },
  '2.2': { agent: agent_8, meta: meta_8 },
  '2.3': { agent: agent_9, meta: meta_9 },
  '2.4': { agent: agent_10, meta: meta_10 },
  '2.5': { agent: agent_11, meta: meta_11 },
  '2.6': { agent: agent_12, meta: meta_12 },
  '3.1': { agent: agent_13, meta: meta_13 },
  '3.2': { agent: agent_14, meta: meta_14 },
  '3.3': { agent: agent_15, meta: meta_15 },
  '3.4': { agent: agent_16, meta: meta_16 },
  '3.5': { agent: agent_17, meta: meta_17 },
  '3.6': { agent: agent_18, meta: meta_18 },
  '4.1': { agent: agent_19, meta: meta_19 },
  '4.2': { agent: agent_20, meta: meta_20 },
  '4.3': { agent: agent_21, meta: meta_21 },
  '4.4': { agent: agent_22, meta: meta_22 },
  '4.5': { agent: agent_23, meta: meta_23 },
  '4.6': { agent: agent_24, meta: meta_24 },
  '4.7': { agent: agent_25, meta: meta_25 },
  '4.8': { agent: agent_26, meta: meta_26 },
  '5.1': { agent: agent_27, meta: meta_27 },
  '5.2': { agent: agent_28, meta: meta_28 },
  '5.3': { agent: agent_29, meta: meta_29 },
  '5.4': { agent: agent_30, meta: meta_30 },
  '5.5': { agent: agent_31, meta: meta_31 },
  '5.6': { agent: agent_32, meta: meta_32 },
  '5.7': { agent: agent_33, meta: meta_33 },
  '6.1': { agent: agent_34, meta: meta_34 },
  '6.2': { agent: agent_35, meta: meta_35 },
  '6.3': { agent: agent_36, meta: meta_36 },
  '6.4': { agent: agent_37, meta: meta_37 },
  '6.5': { agent: agent_38, meta: meta_38 },
  '6.6': { agent: agent_39, meta: meta_39 },
  '6.7': { agent: agent_40, meta: meta_40 },
  '7.1': { agent: agent_41, meta: meta_41 },
  '7.2': { agent: agent_42, meta: meta_42 },
  '7.3': { agent: agent_43, meta: meta_43 },
  '7.4': { agent: agent_44, meta: meta_44 },
  '7.5': { agent: agent_45, meta: meta_45 },
  '7.6': { agent: agent_46, meta: meta_46 },
  '7.7': { agent: agent_47, meta: meta_47 },
  '8.1': { agent: agent_48, meta: meta_48 },
  '8.2': { agent: agent_49, meta: meta_49 },
  '8.3': { agent: agent_50, meta: meta_50 },
  '8.4': { agent: agent_51, meta: meta_51 },
  '9.1': { agent: agent_52, meta: meta_52 },
  '9.2': { agent: agent_53, meta: meta_53 },
  '9.3': { agent: agent_54, meta: meta_54 },
  '9.4': { agent: agent_55, meta: meta_55 },
  '9.5': { agent: agent_56, meta: meta_56 },
  '9.6': { agent: agent_57, meta: meta_57 },
  '9.7': { agent: agent_58, meta: meta_58 },
  '10.1': { agent: agent_59, meta: meta_59 },
  '10.2': { agent: agent_60, meta: meta_60 },
  '10.3': { agent: agent_61, meta: meta_61 },
  '10.4': { agent: agent_62, meta: meta_62 },
  '10.5': { agent: agent_63, meta: meta_63 },
  '10.6': { agent: agent_64, meta: meta_64 },
  '10.7': { agent: agent_65, meta: meta_65 },
  '10.8': { agent: agent_66, meta: meta_66 },
  '10.9': { agent: agent_67, meta: meta_67 },
  '10.10': { agent: agent_68, meta: meta_68 },
  '11.1': { agent: agent_69, meta: meta_69 },
  '11.2': { agent: agent_70, meta: meta_70 },
  '11.3': { agent: agent_71, meta: meta_71 },
  '11.4': { agent: agent_72, meta: meta_72 },
  '11.5': { agent: agent_73, meta: meta_73 },
  '11.6': { agent: agent_74, meta: meta_74 },
  '11.7': { agent: agent_75, meta: meta_75 },
  '11.8': { agent: agent_76, meta: meta_76 },
  '11.9': { agent: agent_77, meta: meta_77 },
  '11.10': { agent: agent_78, meta: meta_78 },
  '12.1': { agent: agent_79, meta: meta_79 },
  '12.2': { agent: agent_80, meta: meta_80 },
  '12.3': { agent: agent_81, meta: meta_81 },
  '12.4': { agent: agent_82, meta: meta_82 },
  '12.5': { agent: agent_83, meta: meta_83 },
  '12.6': { agent: agent_84, meta: meta_84 },
  '12.7': { agent: agent_85, meta: meta_85 },
  '12.8': { agent: agent_86, meta: meta_86 },
  '13.1': { agent: agent_87, meta: meta_87 },
  '13.2': { agent: agent_88, meta: meta_88 },
  '13.3': { agent: agent_89, meta: meta_89 },
  '13.4': { agent: agent_90, meta: meta_90 },
  '13.5': { agent: agent_91, meta: meta_91 },
  '13.6': { agent: agent_92, meta: meta_92 },
  '13.7': { agent: agent_93, meta: meta_93 },
  '13.8': { agent: agent_94, meta: meta_94 },
  '13.9': { agent: agent_95, meta: meta_95 },
  '14.1': { agent: agent_96, meta: meta_96 },
  '14.2': { agent: agent_97, meta: meta_97 },
  '14.3': { agent: agent_98, meta: meta_98 },
  '14.4': { agent: agent_99, meta: meta_99 },
  '14.5': { agent: agent_100, meta: meta_100 },
  '14.6': { agent: agent_101, meta: meta_101 },
  '14.7': { agent: agent_102, meta: meta_102 },
  '15.1': { agent: agent_103, meta: meta_103 },
  '15.2': { agent: agent_104, meta: meta_104 },
  '15.3': { agent: agent_105, meta: meta_105 },
  '15.4': { agent: agent_106, meta: meta_106 },
  '15.5': { agent: agent_107, meta: meta_107 },
  '15.6': { agent: agent_108, meta: meta_108 },
  '15.7': { agent: agent_109, meta: meta_109 },
  '16.1': { agent: agent_110, meta: meta_110 },
  '16.2': { agent: agent_111, meta: meta_111 },
  '16.3': { agent: agent_112, meta: meta_112 },
  '16.4': { agent: agent_113, meta: meta_113 },
  '16.5': { agent: agent_114, meta: meta_114 },
  '17.1': { agent: agent_115, meta: meta_115 },
  '17.2': { agent: agent_116, meta: meta_116 },
  '17.3': { agent: agent_117, meta: meta_117 },
  '17.4': { agent: agent_118, meta: meta_118 },
  '17.5': { agent: agent_119, meta: meta_119 },
  '17.6': { agent: agent_120, meta: meta_120 },
  '17.7': { agent: agent_121, meta: meta_121 },
  '17.8': { agent: agent_122, meta: meta_122 },
  '17.9': { agent: agent_123, meta: meta_123 },
  '17.10': { agent: agent_124, meta: meta_124 },
  '18.1': { agent: agent_125, meta: meta_125 },
  '18.2': { agent: agent_126, meta: meta_126 },
  '18.3': { agent: agent_127, meta: meta_127 },
  '18.4': { agent: agent_128, meta: meta_128 },
  '18.5': { agent: agent_129, meta: meta_129 },
  '18.6': { agent: agent_130, meta: meta_130 },
  '18.7': { agent: agent_131, meta: meta_131 },
  '18.8': { agent: agent_132, meta: meta_132 },
  '18.9': { agent: agent_133, meta: meta_133 },
  '19.1': { agent: agent_134, meta: meta_134 },
  '19.2': { agent: agent_135, meta: meta_135 },
  '19.3': { agent: agent_136, meta: meta_136 },
  '19.4': { agent: agent_137, meta: meta_137 },
  '19.5': { agent: agent_138, meta: meta_138 },
  '19.6': { agent: agent_139, meta: meta_139 },
  '19.7': { agent: agent_140, meta: meta_140 },
  '19.8': { agent: agent_141, meta: meta_141 },
  '19.9': { agent: agent_142, meta: meta_142 },
  '20.1': { agent: agent_143, meta: meta_143 },
  '20.2': { agent: agent_144, meta: meta_144 },
  '20.3': { agent: agent_145, meta: meta_145 },
  '20.4': { agent: agent_146, meta: meta_146 },
  '20.5': { agent: agent_147, meta: meta_147 },
  '20.6': { agent: agent_148, meta: meta_148 },
  '20.7': { agent: agent_149, meta: meta_149 },
};

export function getAgentByRoleId(id) {
  const entry = AGENT_REGISTRY[id];
  if (!entry) throw new Error(`No agent registered for role id "${id}"`);
  return entry;
}
