// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Chief Product Officer" (1.1, Product Management & Strategy)
// Sets overall product vision and portfolio strategy
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import chief_product_officer from '../../skills/chief-product-officer/SKILL.md';

/**
 * Chief Product Officer
 * Area: Product Management & Strategy
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ChiefProductOfficerAgent() {
  useModel('anthropic/claude-opus-4-6');
  useSkill(chief_product_officer);
  useMcpConnection({ name: 'jira', url: 'https://mcp.atlassian.com/jira/mcp', optional: true });
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "Chief Product Officer" role.
Sets overall product vision and portfolio strategy.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
ChiefProductOfficerAgent.agentName = 'chief-product-officer';
export const meta = {
  id: '1.1',
  name: 'Chief Product Officer',
  area: 'Product Management & Strategy',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
