// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Competitive Analyst" (1.6, Product Management & Strategy)
// Monitors competitors and market trends
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import competitive_analyst from '../../skills/competitive-analyst/SKILL.md';

/**
 * Competitive Analyst
 * Area: Product Management & Strategy
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function CompetitiveAnalystAgent() {
  useModel('anthropic/claude-opus-4-6');
  useSkill(competitive_analyst);
  useMcpConnection({ name: 'jira', url: 'https://mcp.atlassian.com/jira/mcp', optional: true });
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "Competitive Analyst" role.
Monitors competitors and market trends.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
CompetitiveAnalystAgent.agentName = 'competitive-analyst';
export const meta = {
  id: '1.6',
  name: 'Competitive Analyst',
  area: 'Product Management & Strategy',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
