// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Product Analyst" (1.5, Product Management & Strategy)
// Analyzes metrics, user data, and product performance
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import product_analyst from '../../skills/product-analyst/SKILL.md';

/**
 * Product Analyst
 * Area: Product Management & Strategy
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ProductAnalystAgent() {
  useModel('anthropic/claude-opus-4-6');
  useSkill(product_analyst);
  useMcpConnection({ name: 'jira', url: 'https://mcp.atlassian.com/jira/mcp', optional: true });
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "Product Analyst" role.
Analyzes metrics, user data, and product performance.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
ProductAnalystAgent.agentName = 'product-analyst';
export const meta = {
  id: '1.5',
  name: 'Product Analyst',
  area: 'Product Management & Strategy',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
