// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Product Manager" (1.2, Product Management & Strategy)
// Owns specific product/feature roadmap and priorities
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import product_manager from '../../skills/product-manager/SKILL.md' with { type: 'skill' };

/**
 * Product Manager
 * Area: Product Management & Strategy
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ProductManagerAgent() {
  useModel('anthropic/claude-opus-4-6');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(product_manager);
  useTool(...defineMcpTools('jira', 'https://mcp.atlassian.com/jira/mcp'));
  useTool(...defineMcpTools('slack', 'https://mcp.slack.com/mcp'));

  return `You are the autonomous agent standing in for the human "Product Manager" role.
Owns specific product/feature roadmap and priorities.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(ProductManagerAgent);
export const meta = {
  id: '1.2',
  name: 'Product Manager',
  area: 'Product Management & Strategy',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
