// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Product Analyst" (1.5, Product Management & Strategy)
// Analyzes metrics, user data, and product performance
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import product_analyst from '../../skills/product-analyst/SKILL.md' with { type: 'skill' };

/**
 * Product Analyst
 * Area: Product Management & Strategy
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ProductAnalystAgent() {
  useModel('anthropic/claude-opus-4-6');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(product_analyst);
  useTool(...defineMcpTools('jira', 'https://mcp.atlassian.com/jira/mcp'));
  useTool(...defineMcpTools('slack', 'https://mcp.slack.com/mcp'));

  return `You are the autonomous agent standing in for the human "Product Analyst" role.
Analyzes metrics, user data, and product performance.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(ProductAnalystAgent);
export const meta = {
  id: '1.5',
  name: 'Product Analyst',
  area: 'Product Management & Strategy',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
