// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "CI/CD Engineer" (10.8, DevOps & Infrastructure)
// Builds and maintains continuous integration pipelines
'use agent';

import { useModel, useSandbox, useSkill, useMcpConnection } from '@flue/runtime';
import { local } from '@flue/runtime/node';
import ci_cd_engineer from '../../skills/ci-cd-engineer/SKILL.md';

/**
 * CI/CD Engineer
 * Area: DevOps & Infrastructure
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function CICDEngineerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(local());
  useSkill(ci_cd_engineer);
  useMcpConnection({ name: 'github', url: 'https://mcp.github.com/mcp', optional: true });
  useMcpConnection({ name: 'cloudflare', url: 'https://bindings.mcp.cloudflare.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "CI/CD Engineer" role.
Builds and maintains continuous integration pipelines.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
CICDEngineerAgent.agentName = 'ci-cd-engineer';
export const meta = {
  id: '10.8',
  name: 'CI/CD Engineer',
  area: 'DevOps & Infrastructure',
  tier: 'container',
  confidenceThreshold: 0.7,
};
