// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Cloud Engineer" (10.4, DevOps & Infrastructure)
// Manages cloud infrastructure (AWS/Azure/GCP)
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import cloud_engineer from '../../skills/cloud-engineer/SKILL.md' with { type: 'skill' };

/**
 * Cloud Engineer
 * Area: DevOps & Infrastructure
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function CloudEngineerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(cloud_engineer);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));
  useTool(...defineMcpTools('cloudflare', 'https://bindings.mcp.cloudflare.com/mcp'));

  return `You are the autonomous agent standing in for the human "Cloud Engineer" role.
Manages cloud infrastructure (AWS/Azure/GCP).
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(CloudEngineerAgent);
export const meta = {
  id: '10.4',
  name: 'Cloud Engineer',
  area: 'DevOps & Infrastructure',
  tier: 'container',
  confidenceThreshold: 0.7,
};
