// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "DevOps Engineer" (10.2, DevOps & Infrastructure)
// Automates deployment and infrastructure
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import devops_engineer from '../../skills/devops-engineer/SKILL.md' with { type: 'skill' };

/**
 * DevOps Engineer
 * Area: DevOps & Infrastructure
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function DevOpsEngineerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(devops_engineer);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));
  useTool(...defineMcpTools('cloudflare', 'https://bindings.mcp.cloudflare.com/mcp'));

  return `You are the autonomous agent standing in for the human "DevOps Engineer" role.
Automates deployment and infrastructure.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(DevOpsEngineerAgent);
export const meta = {
  id: '10.2',
  name: 'DevOps Engineer',
  area: 'DevOps & Infrastructure',
  tier: 'container',
  confidenceThreshold: 0.7,
};
