// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "DevOps Manager" (10.1, DevOps & Infrastructure)
// Leads DevOps team and strategy
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import devops_manager from '../../skills/devops-manager/SKILL.md' with { type: 'skill' };

/**
 * DevOps Manager
 * Area: DevOps & Infrastructure
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function DevOpsManagerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(devops_manager);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));
  useTool(...defineMcpTools('cloudflare', 'https://bindings.mcp.cloudflare.com/mcp'));

  return `You are the autonomous agent standing in for the human "DevOps Manager" role.
Leads DevOps team and strategy.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(DevOpsManagerAgent);
export const meta = {
  id: '10.1',
  name: 'DevOps Manager',
  area: 'DevOps & Infrastructure',
  tier: 'container',
  confidenceThreshold: 0.8,
};
