// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Infrastructure Engineer" (10.7, DevOps & Infrastructure)
// Manages servers, networks, and hardware
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import infrastructure_engineer from '../../skills/infrastructure-engineer/SKILL.md' with { type: 'skill' };

/**
 * Infrastructure Engineer
 * Area: DevOps & Infrastructure
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function InfrastructureEngineerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(infrastructure_engineer);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));
  useTool(...defineMcpTools('cloudflare', 'https://bindings.mcp.cloudflare.com/mcp'));

  return `You are the autonomous agent standing in for the human "Infrastructure Engineer" role.
Manages servers, networks, and hardware.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(InfrastructureEngineerAgent);
export const meta = {
  id: '10.7',
  name: 'Infrastructure Engineer',
  area: 'DevOps & Infrastructure',
  tier: 'container',
  confidenceThreshold: 0.7,
};
