// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Release Manager" (10.6, DevOps & Infrastructure)
// Coordinates software releases and versioning
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import release_manager from '../../skills/release-manager/SKILL.md' with { type: 'skill' };

/**
 * Release Manager
 * Area: DevOps & Infrastructure
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ReleaseManagerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(release_manager);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));
  useTool(...defineMcpTools('cloudflare', 'https://bindings.mcp.cloudflare.com/mcp'));

  return `You are the autonomous agent standing in for the human "Release Manager" role.
Coordinates software releases and versioning.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(ReleaseManagerAgent);
export const meta = {
  id: '10.6',
  name: 'Release Manager',
  area: 'DevOps & Infrastructure',
  tier: 'container',
  confidenceThreshold: 0.8,
};
