// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Site Reliability Engineer (SRE)" (10.3, DevOps & Infrastructure)
// Ensures system reliability and uptime
'use agent';

import { useModel, useSandbox, useSkill, useMcpConnection } from '@flue/runtime';
import { local } from '@flue/runtime/node';
import site_reliability_engineer_sre from '../../skills/site-reliability-engineer-sre/SKILL.md';

/**
 * Site Reliability Engineer (SRE)
 * Area: DevOps & Infrastructure
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function SiteReliabilityEngineerSREAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(local());
  useSkill(site_reliability_engineer_sre);
  useMcpConnection({ name: 'github', url: 'https://mcp.github.com/mcp', optional: true });
  useMcpConnection({ name: 'cloudflare', url: 'https://bindings.mcp.cloudflare.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "Site Reliability Engineer (SRE)" role.
Ensures system reliability and uptime.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
SiteReliabilityEngineerSREAgent.agentName = 'site-reliability-engineer-sre';
export const meta = {
  id: '10.3',
  name: 'Site Reliability Engineer (SRE)',
  area: 'DevOps & Infrastructure',
  tier: 'container',
  confidenceThreshold: 0.7,
};
