// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Community Manager" (19.6, Customer Support)
// Manages user forums and communities
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import community_manager from '../../skills/community-manager/SKILL.md';
import '../../providers/meta.ts';

/**
 * Community Manager
 * Area: Customer Support
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function CommunityManagerAgent() {
  useModel('meta/muse-spark-1.3-contributor');
  useSkill(community_manager);
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });
  useMcpConnection({ name: 'discord', url: 'https://mcp.discord.com/mcp', optional: true });
  useMcpConnection({ name: 'linear', url: 'https://mcp.linear.app/mcp', auth: process.env.LINEAR_API_KEY, optional: true });

  return `You are the autonomous agent standing in for the human "Community Manager" role.
Manages user forums and communities.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
CommunityManagerAgent.agentName = 'community-manager';
export const meta = {
  id: '19.6',
  name: 'Community Manager',
  area: 'Customer Support',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
