// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Community Manager" (19.6, Customer Support)
// Manages user forums and communities
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import community_manager from '../../skills/community-manager/SKILL.md' with { type: 'skill' };

/**
 * Community Manager
 * Area: Customer Support
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function CommunityManagerAgent() {
  useModel('workers-ai/@cf/meta/llama-3.3-70b-instruct');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(community_manager);
  useTool(...defineMcpTools('slack', 'https://mcp.slack.com/mcp'));
  useTool(...defineMcpTools('discord', 'https://mcp.discord.com/mcp'));

  return `You are the autonomous agent standing in for the human "Community Manager" role.
Manages user forums and communities.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(CommunityManagerAgent);
export const meta = {
  id: '19.6',
  name: 'Community Manager',
  area: 'Customer Support',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
