// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Customer Support Rep (Tier 1)" (19.2, Customer Support)
// Handles basic customer inquiries
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import customer_support_rep_tier_1 from '../../skills/customer-support-rep-tier-1/SKILL.md' with { type: 'skill' };

/**
 * Customer Support Rep (Tier 1)
 * Area: Customer Support
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function CustomerSupportRepTier1Agent() {
  useModel('workers-ai/@cf/meta/llama-3.3-70b-instruct');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(customer_support_rep_tier_1);
  useTool(...defineMcpTools('slack', 'https://mcp.slack.com/mcp'));
  useTool(...defineMcpTools('discord', 'https://mcp.discord.com/mcp'));

  return `You are the autonomous agent standing in for the human "Customer Support Rep (Tier 1)" role.
Handles basic customer inquiries.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(CustomerSupportRepTier1Agent);
export const meta = {
  id: '19.2',
  name: 'Customer Support Rep (Tier 1)',
  area: 'Customer Support',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
