// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Customer Advocate" (19.7, Customer Support)
// Represents customer needs internally
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import customer_advocate from '../../skills/customer-advocate/SKILL.md';

/**
 * Customer Advocate
 * Area: Customer Support
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function CustomerAdvocateAgent() {
  useModel('cloudflare/@cf/meta/llama-3.3-70b-instruct');
  useSkill(customer_advocate);
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });
  useMcpConnection({ name: 'discord', url: 'https://mcp.discord.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "Customer Advocate" role.
Represents customer needs internally.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
CustomerAdvocateAgent.agentName = 'customer-advocate';
export const meta = {
  id: '19.7',
  name: 'Customer Advocate',
  area: 'Customer Support',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
