// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Customer Advocate" (19.7, Customer Support)
// Represents customer needs internally
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import customer_advocate from '../../skills/customer-advocate/SKILL.md' with { type: 'skill' };

/**
 * Customer Advocate
 * Area: Customer Support
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function CustomerAdvocateAgent() {
  useModel('workers-ai/@cf/meta/llama-3.3-70b-instruct');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(customer_advocate);
  useTool(...defineMcpTools('slack', 'https://mcp.slack.com/mcp'));
  useTool(...defineMcpTools('discord', 'https://mcp.discord.com/mcp'));

  return `You are the autonomous agent standing in for the human "Customer Advocate" role.
Represents customer needs internally.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(CustomerAdvocateAgent);
export const meta = {
  id: '19.7',
  name: 'Customer Advocate',
  area: 'Customer Support',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
