// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Customer Support Rep (Tier 1)" (19.2, Customer Support)
// Handles basic customer inquiries
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import customer_support_rep_tier_1 from '../../skills/customer-support-rep-tier-1/SKILL.md';
import '../../providers/meta.ts';

/**
 * Customer Support Rep (Tier 1)
 * Area: Customer Support
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function CustomerSupportRepTier1Agent() {
  useModel('meta/muse-spark-1.3-contributor');
  useSkill(customer_support_rep_tier_1);
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });
  useMcpConnection({ name: 'discord', url: 'https://mcp.discord.com/mcp', optional: true });
  useMcpConnection({ name: 'linear', url: 'https://mcp.linear.app/mcp', auth: process.env.LINEAR_API_KEY, optional: true });

  return `You are the autonomous agent standing in for the human "Customer Support Rep (Tier 1)" role.
Handles basic customer inquiries.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
CustomerSupportRepTier1Agent.agentName = 'customer-support-rep-tier-1';
export const meta = {
  id: '19.2',
  name: 'Customer Support Rep (Tier 1)',
  area: 'Customer Support',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
