// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Head of Support" (19.1, Customer Support)
// Leads customer support organization
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import head_of_support from '../../skills/head-of-support/SKILL.md';

/**
 * Head of Support
 * Area: Customer Support
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function HeadOfSupportAgent() {
  useModel('cloudflare/@cf/meta/llama-3.3-70b-instruct');
  useSkill(head_of_support);
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });
  useMcpConnection({ name: 'discord', url: 'https://mcp.discord.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "Head of Support" role.
Leads customer support organization.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
HeadOfSupportAgent.agentName = 'head-of-support';
export const meta = {
  id: '19.1',
  name: 'Head of Support',
  area: 'Customer Support',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
