// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Senior Support Engineer (Tier 3)" (19.4, Customer Support)
// Handles escalations and critical issues
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import senior_support_engineer_tier_3 from '../../skills/senior-support-engineer-tier-3/SKILL.md' with { type: 'skill' };

/**
 * Senior Support Engineer (Tier 3)
 * Area: Customer Support
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function SeniorSupportEngineerTier3Agent() {
  useModel('workers-ai/@cf/meta/llama-3.3-70b-instruct');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(senior_support_engineer_tier_3);
  useTool(...defineMcpTools('slack', 'https://mcp.slack.com/mcp'));
  useTool(...defineMcpTools('discord', 'https://mcp.discord.com/mcp'));

  return `You are the autonomous agent standing in for the human "Senior Support Engineer (Tier 3)" role.
Handles escalations and critical issues.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(SeniorSupportEngineerTier3Agent);
export const meta = {
  id: '19.4',
  name: 'Senior Support Engineer (Tier 3)',
  area: 'Customer Support',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
