// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Support Operations Manager" (19.5, Customer Support)
// Optimizes support workflows and metrics
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import support_operations_manager from '../../skills/support-operations-manager/SKILL.md';
import '../../providers/meta.ts';

/**
 * Support Operations Manager
 * Area: Customer Support
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function SupportOperationsManagerAgent() {
  useModel('meta/muse-spark-1.3-contributor');
  useSkill(support_operations_manager);
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });
  useMcpConnection({ name: 'discord', url: 'https://mcp.discord.com/mcp', optional: true });
  useMcpConnection({ name: 'linear', url: 'https://mcp.linear.app/mcp', auth: process.env.LINEAR_API_KEY, optional: true });

  return `You are the autonomous agent standing in for the human "Support Operations Manager" role.
Optimizes support workflows and metrics.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
SupportOperationsManagerAgent.agentName = 'support-operations-manager';
export const meta = {
  id: '19.5',
  name: 'Support Operations Manager',
  area: 'Customer Support',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
