// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Technical Support Engineer (Tier 2)" (19.3, Customer Support)
// Resolves complex technical issues
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import technical_support_engineer_tier_2 from '../../skills/technical-support-engineer-tier-2/SKILL.md' with { type: 'skill' };

/**
 * Technical Support Engineer (Tier 2)
 * Area: Customer Support
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function TechnicalSupportEngineerTier2Agent() {
  useModel('workers-ai/@cf/meta/llama-3.3-70b-instruct');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(technical_support_engineer_tier_2);
  useTool(...defineMcpTools('slack', 'https://mcp.slack.com/mcp'));
  useTool(...defineMcpTools('discord', 'https://mcp.discord.com/mcp'));

  return `You are the autonomous agent standing in for the human "Technical Support Engineer (Tier 2)" role.
Resolves complex technical issues.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(TechnicalSupportEngineerTier2Agent);
export const meta = {
  id: '19.3',
  name: 'Technical Support Engineer (Tier 2)',
  area: 'Customer Support',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
