// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Training Specialist" (19.9, Customer Support)
// Educates customers on product features
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import training_specialist from '../../skills/training-specialist/SKILL.md' with { type: 'skill' };

/**
 * Training Specialist
 * Area: Customer Support
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function TrainingSpecialistAgent() {
  useModel('workers-ai/@cf/meta/llama-3.3-70b-instruct');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(training_specialist);
  useTool(...defineMcpTools('slack', 'https://mcp.slack.com/mcp'));
  useTool(...defineMcpTools('discord', 'https://mcp.discord.com/mcp'));

  return `You are the autonomous agent standing in for the human "Training Specialist" role.
Educates customers on product features.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(TrainingSpecialistAgent);
export const meta = {
  id: '19.9',
  name: 'Training Specialist',
  area: 'Customer Support',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
