// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Account Manager" (18.7, Sales)
// Manages existing customer relationships
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import account_manager from '../../skills/account-manager/SKILL.md';

/**
 * Account Manager
 * Area: Sales
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function AccountManagerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSkill(account_manager);
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });
  useMcpConnection({ name: 'gdrive', url: 'https://drivemcp.googleapis.com/mcp/v1', optional: true });

  return `You are the autonomous agent standing in for the human "Account Manager" role.
Manages existing customer relationships.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
AccountManagerAgent.agentName = 'account-manager';
export const meta = {
  id: '18.7',
  name: 'Account Manager',
  area: 'Sales',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
