// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Customer Success Manager" (18.6, Sales)
// Ensures customer satisfaction and retention
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import customer_success_manager from '../../skills/customer-success-manager/SKILL.md' with { type: 'skill' };

/**
 * Customer Success Manager
 * Area: Sales
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function CustomerSuccessManagerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(customer_success_manager);
  useTool(...defineMcpTools('slack', 'https://mcp.slack.com/mcp'));
  useTool(...defineMcpTools('gdrive', 'https://drivemcp.googleapis.com/mcp/v1'));

  return `You are the autonomous agent standing in for the human "Customer Success Manager" role.
Ensures customer satisfaction and retention.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(CustomerSuccessManagerAgent);
export const meta = {
  id: '18.6',
  name: 'Customer Success Manager',
  area: 'Sales',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
