// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Customer Success Manager" (18.6, Sales)
// Ensures customer satisfaction and retention
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import customer_success_manager from '../../skills/customer-success-manager/SKILL.md';

/**
 * Customer Success Manager
 * Area: Sales
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function CustomerSuccessManagerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSkill(customer_success_manager);
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });
  useMcpConnection({ name: 'gdrive', url: 'https://drivemcp.googleapis.com/mcp/v1', optional: true });

  return `You are the autonomous agent standing in for the human "Customer Success Manager" role.
Ensures customer satisfaction and retention.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
CustomerSuccessManagerAgent.agentName = 'customer-success-manager';
export const meta = {
  id: '18.6',
  name: 'Customer Success Manager',
  area: 'Sales',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
