// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Enterprise Sales Rep" (18.4, Sales)
// Sells to large enterprise customers
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import enterprise_sales_rep from '../../skills/enterprise-sales-rep/SKILL.md' with { type: 'skill' };

/**
 * Enterprise Sales Rep
 * Area: Sales
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function EnterpriseSalesRepAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(enterprise_sales_rep);
  useTool(...defineMcpTools('slack', 'https://mcp.slack.com/mcp'));
  useTool(...defineMcpTools('gdrive', 'https://drivemcp.googleapis.com/mcp/v1'));

  return `You are the autonomous agent standing in for the human "Enterprise Sales Rep" role.
Sells to large enterprise customers.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(EnterpriseSalesRepAgent);
export const meta = {
  id: '18.4',
  name: 'Enterprise Sales Rep',
  area: 'Sales',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
