// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Sales Development Rep (SDR)" (18.2, Sales)
// Qualifies leads and books meetings
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import sales_development_rep_sdr from '../../skills/sales-development-rep-sdr/SKILL.md' with { type: 'skill' };

/**
 * Sales Development Rep (SDR)
 * Area: Sales
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function SalesDevelopmentRepSDRAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(sales_development_rep_sdr);
  useTool(...defineMcpTools('slack', 'https://mcp.slack.com/mcp'));
  useTool(...defineMcpTools('gdrive', 'https://drivemcp.googleapis.com/mcp/v1'));

  return `You are the autonomous agent standing in for the human "Sales Development Rep (SDR)" role.
Qualifies leads and books meetings.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(SalesDevelopmentRepSDRAgent);
export const meta = {
  id: '18.2',
  name: 'Sales Development Rep (SDR)',
  area: 'Sales',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
