// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Sales Operations Analyst" (18.8, Sales)
// Optimizes sales processes and tools
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import sales_operations_analyst from '../../skills/sales-operations-analyst/SKILL.md';

/**
 * Sales Operations Analyst
 * Area: Sales
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function SalesOperationsAnalystAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSkill(sales_operations_analyst);
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });
  useMcpConnection({ name: 'gdrive', url: 'https://drivemcp.googleapis.com/mcp/v1', optional: true });

  return `You are the autonomous agent standing in for the human "Sales Operations Analyst" role.
Optimizes sales processes and tools.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
SalesOperationsAnalystAgent.agentName = 'sales-operations-analyst';
export const meta = {
  id: '18.8',
  name: 'Sales Operations Analyst',
  area: 'Sales',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
