// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Sales Operations Analyst" (18.8, Sales)
// Optimizes sales processes and tools
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import sales_operations_analyst from '../../skills/sales-operations-analyst/SKILL.md' with { type: 'skill' };

/**
 * Sales Operations Analyst
 * Area: Sales
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function SalesOperationsAnalystAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(sales_operations_analyst);
  useTool(...defineMcpTools('slack', 'https://mcp.slack.com/mcp'));
  useTool(...defineMcpTools('gdrive', 'https://drivemcp.googleapis.com/mcp/v1'));

  return `You are the autonomous agent standing in for the human "Sales Operations Analyst" role.
Optimizes sales processes and tools.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(SalesOperationsAnalystAgent);
export const meta = {
  id: '18.8',
  name: 'Sales Operations Analyst',
  area: 'Sales',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
