// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Solutions Engineer/Sales Engineer" (18.5, Sales)
// Provides technical expertise in sales
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import solutions_engineer_sales_engineer from '../../skills/solutions-engineer-sales-engineer/SKILL.md' with { type: 'skill' };

/**
 * Solutions Engineer/Sales Engineer
 * Area: Sales
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function SolutionsEngineerSalesEngineerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(solutions_engineer_sales_engineer);
  useTool(...defineMcpTools('slack', 'https://mcp.slack.com/mcp'));
  useTool(...defineMcpTools('gdrive', 'https://drivemcp.googleapis.com/mcp/v1'));

  return `You are the autonomous agent standing in for the human "Solutions Engineer/Sales Engineer" role.
Provides technical expertise in sales.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(SolutionsEngineerSalesEngineerAgent);
export const meta = {
  id: '18.5',
  name: 'Solutions Engineer/Sales Engineer',
  area: 'Sales',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
