// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Solutions Engineer/Sales Engineer" (18.5, Sales)
// Provides technical expertise in sales
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import solutions_engineer_sales_engineer from '../../skills/solutions-engineer-sales-engineer/SKILL.md';

/**
 * Solutions Engineer/Sales Engineer
 * Area: Sales
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function SolutionsEngineerSalesEngineerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSkill(solutions_engineer_sales_engineer);
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });
  useMcpConnection({ name: 'gdrive', url: 'https://drivemcp.googleapis.com/mcp/v1', optional: true });

  return `You are the autonomous agent standing in for the human "Solutions Engineer/Sales Engineer" role.
Provides technical expertise in sales.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
SolutionsEngineerSalesEngineerAgent.agentName = 'solutions-engineer-sales-engineer';
export const meta = {
  id: '18.5',
  name: 'Solutions Engineer/Sales Engineer',
  area: 'Sales',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
