// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Analytics Engineer" (13.9, Data Engineering & Analytics)
// Transforms raw data into analytics-ready datasets
'use agent';

import { useModel, useSandbox, useSkill, useMcpConnection } from '@flue/runtime';
import { local } from '@flue/runtime/node';
import analytics_engineer from '../../skills/analytics-engineer/SKILL.md';

/**
 * Analytics Engineer
 * Area: Data Engineering & Analytics
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function AnalyticsEngineerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(local());
  useSkill(analytics_engineer);
  useMcpConnection({ name: 'github', url: 'https://mcp.github.com/mcp', optional: true });
  useMcpConnection({ name: 'gdrive', url: 'https://drivemcp.googleapis.com/mcp/v1', optional: true });

  return `You are the autonomous agent standing in for the human "Analytics Engineer" role.
Transforms raw data into analytics-ready datasets.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
AnalyticsEngineerAgent.agentName = 'analytics-engineer';
export const meta = {
  id: '13.9',
  name: 'Analytics Engineer',
  area: 'Data Engineering & Analytics',
  tier: 'container',
  confidenceThreshold: 0.7,
};
