// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Data Scientist" (13.7, Data Engineering & Analytics)
// Develops predictive models and ML algorithms
'use agent';

import { useModel, useSandbox, useSkill, useMcpConnection } from '@flue/runtime';
import { local } from '@flue/runtime/node';
import data_scientist from '../../skills/data-scientist/SKILL.md';

/**
 * Data Scientist
 * Area: Data Engineering & Analytics
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function DataScientistAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(local());
  useSkill(data_scientist);
  useMcpConnection({ name: 'github', url: 'https://mcp.github.com/mcp', optional: true });
  useMcpConnection({ name: 'gdrive', url: 'https://drivemcp.googleapis.com/mcp/v1', optional: true });

  return `You are the autonomous agent standing in for the human "Data Scientist" role.
Develops predictive models and ML algorithms.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
DataScientistAgent.agentName = 'data-scientist';
export const meta = {
  id: '13.7',
  name: 'Data Scientist',
  area: 'Data Engineering & Analytics',
  tier: 'container',
  confidenceThreshold: 0.7,
};
