// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Data Analyst" (13.5, Data Engineering & Analytics)
// Analyzes data and creates reports
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import data_analyst from '../../skills/data-analyst/SKILL.md' with { type: 'skill' };

/**
 * Data Analyst
 * Area: Data Engineering & Analytics
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function DataAnalystAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(data_analyst);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));
  useTool(...defineMcpTools('gdrive', 'https://drivemcp.googleapis.com/mcp/v1'));

  return `You are the autonomous agent standing in for the human "Data Analyst" role.
Analyzes data and creates reports.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(DataAnalystAgent);
export const meta = {
  id: '13.5',
  name: 'Data Analyst',
  area: 'Data Engineering & Analytics',
  tier: 'container',
  confidenceThreshold: 0.7,
};
