// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Accessibility Specialist" (3.4, User Research & Experience)
// Ensures product accessibility (WCAG compliance)
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import accessibility_specialist from '../../skills/accessibility-specialist/SKILL.md' with { type: 'skill' };

/**
 * Accessibility Specialist
 * Area: User Research & Experience
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function AccessibilitySpecialistAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(accessibility_specialist);
  useTool(...defineMcpTools('figma', 'https://mcp.figma.com/mcp'));
  useTool(...defineMcpTools('slack', 'https://mcp.slack.com/mcp'));

  return `You are the autonomous agent standing in for the human "Accessibility Specialist" role.
Ensures product accessibility (WCAG compliance).
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(AccessibilitySpecialistAgent);
export const meta = {
  id: '3.4',
  name: 'Accessibility Specialist',
  area: 'User Research & Experience',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
