// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Accessibility Specialist" (3.4, User Research & Experience)
// Ensures product accessibility (WCAG compliance)
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import accessibility_specialist from '../../skills/accessibility-specialist/SKILL.md';

/**
 * Accessibility Specialist
 * Area: User Research & Experience
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function AccessibilitySpecialistAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSkill(accessibility_specialist);
  useMcpConnection({ name: 'figma', url: 'https://mcp.figma.com/mcp', optional: true });
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "Accessibility Specialist" role.
Ensures product accessibility (WCAG compliance).
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
AccessibilitySpecialistAgent.agentName = 'accessibility-specialist';
export const meta = {
  id: '3.4',
  name: 'Accessibility Specialist',
  area: 'User Research & Experience',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
