// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Information Architect" (3.5, User Research & Experience)
// Organizes content structure and navigation
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import information_architect from '../../skills/information-architect/SKILL.md';

/**
 * Information Architect
 * Area: User Research & Experience
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function InformationArchitectAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSkill(information_architect);
  useMcpConnection({ name: 'figma', url: 'https://mcp.figma.com/mcp', optional: true });
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "Information Architect" role.
Organizes content structure and navigation.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
InformationArchitectAgent.agentName = 'information-architect';
export const meta = {
  id: '3.5',
  name: 'Information Architect',
  area: 'User Research & Experience',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
