// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Usability Tester" (3.6, User Research & Experience)
// Facilitates and analyzes usability testing sessions
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import usability_tester from '../../skills/usability-tester/SKILL.md';

/**
 * Usability Tester
 * Area: User Research & Experience
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function UsabilityTesterAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSkill(usability_tester);
  useMcpConnection({ name: 'figma', url: 'https://mcp.figma.com/mcp', optional: true });
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "Usability Tester" role.
Facilitates and analyzes usability testing sessions.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
UsabilityTesterAgent.agentName = 'usability-tester';
export const meta = {
  id: '3.6',
  name: 'Usability Tester',
  area: 'User Research & Experience',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
