// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "UX Research Lead" (3.1, User Research & Experience)
// Directs research strategy and methodologies
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import ux_research_lead from '../../skills/ux-research-lead/SKILL.md' with { type: 'skill' };

/**
 * UX Research Lead
 * Area: User Research & Experience
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function UXResearchLeadAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(ux_research_lead);
  useTool(...defineMcpTools('figma', 'https://mcp.figma.com/mcp'));
  useTool(...defineMcpTools('slack', 'https://mcp.slack.com/mcp'));

  return `You are the autonomous agent standing in for the human "UX Research Lead" role.
Directs research strategy and methodologies.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(UXResearchLeadAgent);
export const meta = {
  id: '3.1',
  name: 'UX Research Lead',
  area: 'User Research & Experience',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
