// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "CSS/Styling Specialist" (6.4, Frontend Development)
// Expert in styling, animations, and responsive design
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import css_styling_specialist from '../../skills/css-styling-specialist/SKILL.md' with { type: 'skill' };

/**
 * CSS/Styling Specialist
 * Area: Frontend Development
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function CSSStylingSpecialistAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(css_styling_specialist);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));
  useTool(...defineMcpTools('figma', 'https://mcp.figma.com/mcp'));

  return `You are the autonomous agent standing in for the human "CSS/Styling Specialist" role.
Expert in styling, animations, and responsive design.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(CSSStylingSpecialistAgent);
export const meta = {
  id: '6.4',
  name: 'CSS/Styling Specialist',
  area: 'Frontend Development',
  tier: 'container',
  confidenceThreshold: 0.7,
};
