// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Frontend Performance Engineer" (6.5, Frontend Development)
// Optimizes load times and runtime performance
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import frontend_performance_engineer from '../../skills/frontend-performance-engineer/SKILL.md' with { type: 'skill' };

/**
 * Frontend Performance Engineer
 * Area: Frontend Development
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function FrontendPerformanceEngineerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(frontend_performance_engineer);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));
  useTool(...defineMcpTools('figma', 'https://mcp.figma.com/mcp'));

  return `You are the autonomous agent standing in for the human "Frontend Performance Engineer" role.
Optimizes load times and runtime performance.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(FrontendPerformanceEngineerAgent);
export const meta = {
  id: '6.5',
  name: 'Frontend Performance Engineer',
  area: 'Frontend Development',
  tier: 'container',
  confidenceThreshold: 0.7,
};
