// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Frontend Lead/Principal" (6.1, Frontend Development)
// Leads frontend team and technical decisions
'use agent';

import { useModel, useSandbox, useSkill, useMcpConnection } from '@flue/runtime';
import { local } from '@flue/runtime/node';
import frontend_lead_principal from '../../skills/frontend-lead-principal/SKILL.md';

/**
 * Frontend Lead/Principal
 * Area: Frontend Development
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function FrontendLeadPrincipalAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(local());
  useSkill(frontend_lead_principal);
  useMcpConnection({ name: 'github', url: 'https://mcp.github.com/mcp', optional: true });
  useMcpConnection({ name: 'figma', url: 'https://mcp.figma.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "Frontend Lead/Principal" role.
Leads frontend team and technical decisions.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
FrontendLeadPrincipalAgent.agentName = 'frontend-lead-principal';
export const meta = {
  id: '6.1',
  name: 'Frontend Lead/Principal',
  area: 'Frontend Development',
  tier: 'container',
  confidenceThreshold: 0.8,
};
