// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "JavaScript/TypeScript Developer" (6.3, Frontend Development)
// Specializes in JS frameworks (React, Vue, Angular)
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import javascript_typescript_developer from '../../skills/javascript-typescript-developer/SKILL.md' with { type: 'skill' };

/**
 * JavaScript/TypeScript Developer
 * Area: Frontend Development
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function JavaScriptTypeScriptDeveloperAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(javascript_typescript_developer);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));
  useTool(...defineMcpTools('figma', 'https://mcp.figma.com/mcp'));

  return `You are the autonomous agent standing in for the human "JavaScript/TypeScript Developer" role.
Specializes in JS frameworks (React, Vue, Angular).
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(JavaScriptTypeScriptDeveloperAgent);
export const meta = {
  id: '6.3',
  name: 'JavaScript/TypeScript Developer',
  area: 'Frontend Development',
  tier: 'container',
  confidenceThreshold: 0.7,
};
