// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "JavaScript/TypeScript Developer" (6.3, Frontend Development)
// Specializes in JS frameworks (React, Vue, Angular)
'use agent';

import { useModel, useSandbox, useSkill, useMcpConnection } from '@flue/runtime';
import { local } from '@flue/runtime/node';
import javascript_typescript_developer from '../../skills/javascript-typescript-developer/SKILL.md';

/**
 * JavaScript/TypeScript Developer
 * Area: Frontend Development
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function JavaScriptTypeScriptDeveloperAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(local());
  useSkill(javascript_typescript_developer);
  useMcpConnection({ name: 'github', url: 'https://mcp.github.com/mcp', optional: true });
  useMcpConnection({ name: 'figma', url: 'https://mcp.figma.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "JavaScript/TypeScript Developer" role.
Specializes in JS frameworks (React, Vue, Angular).
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
JavaScriptTypeScriptDeveloperAgent.agentName = 'javascript-typescript-developer';
export const meta = {
  id: '6.3',
  name: 'JavaScript/TypeScript Developer',
  area: 'Frontend Development',
  tier: 'container',
  confidenceThreshold: 0.7,
};
