// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Web Accessibility Developer" (6.6, Frontend Development)
// Implements ARIA and accessibility features
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import web_accessibility_developer from '../../skills/web-accessibility-developer/SKILL.md' with { type: 'skill' };

/**
 * Web Accessibility Developer
 * Area: Frontend Development
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function WebAccessibilityDeveloperAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(web_accessibility_developer);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));
  useTool(...defineMcpTools('figma', 'https://mcp.figma.com/mcp'));

  return `You are the autonomous agent standing in for the human "Web Accessibility Developer" role.
Implements ARIA and accessibility features.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(WebAccessibilityDeveloperAgent);
export const meta = {
  id: '6.6',
  name: 'Web Accessibility Developer',
  area: 'Frontend Development',
  tier: 'container',
  confidenceThreshold: 0.7,
};
