// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Compliance Manager" (20.5, Legal & Compliance)
// Maintains regulatory compliance
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import compliance_manager from '../../skills/compliance-manager/SKILL.md' with { type: 'skill' };

/**
 * Compliance Manager
 * Area: Legal & Compliance
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ComplianceManagerAgent() {
  useModel('anthropic/claude-opus-4-6');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(compliance_manager);
  useTool(...defineMcpTools('gdrive', 'https://drivemcp.googleapis.com/mcp/v1'));

  return `You are the autonomous agent standing in for the human "Compliance Manager" role.
Maintains regulatory compliance.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(ComplianceManagerAgent);
export const meta = {
  id: '20.5',
  name: 'Compliance Manager',
  area: 'Legal & Compliance',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
