// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Compliance Manager" (20.5, Legal & Compliance)
// Maintains regulatory compliance
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import compliance_manager from '../../skills/compliance-manager/SKILL.md';

/**
 * Compliance Manager
 * Area: Legal & Compliance
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ComplianceManagerAgent() {
  useModel('anthropic/claude-opus-4-6');
  useSkill(compliance_manager);
  useMcpConnection({ name: 'gdrive', url: 'https://drivemcp.googleapis.com/mcp/v1', optional: true });

  return `You are the autonomous agent standing in for the human "Compliance Manager" role.
Maintains regulatory compliance.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
ComplianceManagerAgent.agentName = 'compliance-manager';
export const meta = {
  id: '20.5',
  name: 'Compliance Manager',
  area: 'Legal & Compliance',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
