// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Contract Manager" (20.6, Legal & Compliance)
// Manages contract lifecycle and negotiations
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import contract_manager from '../../skills/contract-manager/SKILL.md' with { type: 'skill' };

/**
 * Contract Manager
 * Area: Legal & Compliance
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ContractManagerAgent() {
  useModel('anthropic/claude-opus-4-6');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(contract_manager);
  useTool(...defineMcpTools('gdrive', 'https://drivemcp.googleapis.com/mcp/v1'));

  return `You are the autonomous agent standing in for the human "Contract Manager" role.
Manages contract lifecycle and negotiations.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(ContractManagerAgent);
export const meta = {
  id: '20.6',
  name: 'Contract Manager',
  area: 'Legal & Compliance',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
