// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Corporate Lawyer" (20.2, Legal & Compliance)
// Handles contracts and business agreements
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import corporate_lawyer from '../../skills/corporate-lawyer/SKILL.md';

/**
 * Corporate Lawyer
 * Area: Legal & Compliance
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function CorporateLawyerAgent() {
  useModel('anthropic/claude-opus-4-6');
  useSkill(corporate_lawyer);
  useMcpConnection({ name: 'gdrive', url: 'https://drivemcp.googleapis.com/mcp/v1', optional: true });

  return `You are the autonomous agent standing in for the human "Corporate Lawyer" role.
Handles contracts and business agreements.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
CorporateLawyerAgent.agentName = 'corporate-lawyer';
export const meta = {
  id: '20.2',
  name: 'Corporate Lawyer',
  area: 'Legal & Compliance',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
