// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "General Counsel" (20.1, Legal & Compliance)
// Oversees all legal matters
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import general_counsel from '../../skills/general-counsel/SKILL.md' with { type: 'skill' };

/**
 * General Counsel
 * Area: Legal & Compliance
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function GeneralCounselAgent() {
  useModel('anthropic/claude-opus-4-6');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(general_counsel);
  useTool(...defineMcpTools('gdrive', 'https://drivemcp.googleapis.com/mcp/v1'));

  return `You are the autonomous agent standing in for the human "General Counsel" role.
Oversees all legal matters.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(GeneralCounselAgent);
export const meta = {
  id: '20.1',
  name: 'General Counsel',
  area: 'Legal & Compliance',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
