// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Paralegal" (20.7, Legal & Compliance)
// Supports legal team with documentation
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import paralegal from '../../skills/paralegal/SKILL.md';

/**
 * Paralegal
 * Area: Legal & Compliance
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ParalegalAgent() {
  useModel('anthropic/claude-opus-4-6');
  useSkill(paralegal);
  useMcpConnection({ name: 'gdrive', url: 'https://drivemcp.googleapis.com/mcp/v1', optional: true });

  return `You are the autonomous agent standing in for the human "Paralegal" role.
Supports legal team with documentation.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
ParalegalAgent.agentName = 'paralegal';
export const meta = {
  id: '20.7',
  name: 'Paralegal',
  area: 'Legal & Compliance',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
