// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Agile Transformation Lead" (16.5, Agile & Scrum)
// Drives organizational agile adoption
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import agile_transformation_lead from '../../skills/agile-transformation-lead/SKILL.md';

/**
 * Agile Transformation Lead
 * Area: Agile & Scrum
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function AgileTransformationLeadAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSkill(agile_transformation_lead);
  useMcpConnection({ name: 'jira', url: 'https://mcp.atlassian.com/jira/mcp', optional: true });
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "Agile Transformation Lead" role.
Drives organizational agile adoption.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
AgileTransformationLeadAgent.agentName = 'agile-transformation-lead';
export const meta = {
  id: '16.5',
  name: 'Agile Transformation Lead',
  area: 'Agile & Scrum',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
