// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Agile Transformation Lead" (16.5, Agile & Scrum)
// Drives organizational agile adoption
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import agile_transformation_lead from '../../skills/agile-transformation-lead/SKILL.md' with { type: 'skill' };

/**
 * Agile Transformation Lead
 * Area: Agile & Scrum
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function AgileTransformationLeadAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(agile_transformation_lead);
  useTool(...defineMcpTools('jira', 'https://mcp.atlassian.com/jira/mcp'));
  useTool(...defineMcpTools('slack', 'https://mcp.slack.com/mcp'));

  return `You are the autonomous agent standing in for the human "Agile Transformation Lead" role.
Drives organizational agile adoption.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(AgileTransformationLeadAgent);
export const meta = {
  id: '16.5',
  name: 'Agile Transformation Lead',
  area: 'Agile & Scrum',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
