// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Kanban Lead" (16.3, Agile & Scrum)
// Manages kanban workflow and optimization
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import kanban_lead from '../../skills/kanban-lead/SKILL.md' with { type: 'skill' };

/**
 * Kanban Lead
 * Area: Agile & Scrum
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function KanbanLeadAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(kanban_lead);
  useTool(...defineMcpTools('jira', 'https://mcp.atlassian.com/jira/mcp'));
  useTool(...defineMcpTools('slack', 'https://mcp.slack.com/mcp'));

  return `You are the autonomous agent standing in for the human "Kanban Lead" role.
Manages kanban workflow and optimization.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(KanbanLeadAgent);
export const meta = {
  id: '16.3',
  name: 'Kanban Lead',
  area: 'Agile & Scrum',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
