// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Kanban Lead" (16.3, Agile & Scrum)
// Manages kanban workflow and optimization
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import kanban_lead from '../../skills/kanban-lead/SKILL.md';

/**
 * Kanban Lead
 * Area: Agile & Scrum
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function KanbanLeadAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSkill(kanban_lead);
  useMcpConnection({ name: 'jira', url: 'https://mcp.atlassian.com/jira/mcp', optional: true });
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "Kanban Lead" role.
Manages kanban workflow and optimization.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
KanbanLeadAgent.agentName = 'kanban-lead';
export const meta = {
  id: '16.3',
  name: 'Kanban Lead',
  area: 'Agile & Scrum',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
