// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Release Train Engineer" (16.4, Agile & Scrum)
// Coordinates agile release trains (SAFe)
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import release_train_engineer from '../../skills/release-train-engineer/SKILL.md' with { type: 'skill' };

/**
 * Release Train Engineer
 * Area: Agile & Scrum
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ReleaseTrainEngineerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(release_train_engineer);
  useTool(...defineMcpTools('jira', 'https://mcp.atlassian.com/jira/mcp'));
  useTool(...defineMcpTools('slack', 'https://mcp.slack.com/mcp'));

  return `You are the autonomous agent standing in for the human "Release Train Engineer" role.
Coordinates agile release trains (SAFe).
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(ReleaseTrainEngineerAgent);
export const meta = {
  id: '16.4',
  name: 'Release Train Engineer',
  area: 'Agile & Scrum',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
