// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Release Train Engineer" (16.4, Agile & Scrum)
// Coordinates agile release trains (SAFe)
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import release_train_engineer from '../../skills/release-train-engineer/SKILL.md';

/**
 * Release Train Engineer
 * Area: Agile & Scrum
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ReleaseTrainEngineerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSkill(release_train_engineer);
  useMcpConnection({ name: 'jira', url: 'https://mcp.atlassian.com/jira/mcp', optional: true });
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "Release Train Engineer" role.
Coordinates agile release trains (SAFe).
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
ReleaseTrainEngineerAgent.agentName = 'release-train-engineer';
export const meta = {
  id: '16.4',
  name: 'Release Train Engineer',
  area: 'Agile & Scrum',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
