// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Scrum Master" (16.2, Agile & Scrum)
// Facilitates scrum ceremonies and removes blockers
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import scrum_master from '../../skills/scrum-master/SKILL.md';

/**
 * Scrum Master
 * Area: Agile & Scrum
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ScrumMasterAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSkill(scrum_master);
  useMcpConnection({ name: 'jira', url: 'https://mcp.atlassian.com/jira/mcp', optional: true });
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "Scrum Master" role.
Facilitates scrum ceremonies and removes blockers.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
ScrumMasterAgent.agentName = 'scrum-master';
export const meta = {
  id: '16.2',
  name: 'Scrum Master',
  area: 'Agile & Scrum',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
