// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "PMO Analyst" (15.6, Project Management)
// Supports project management office
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import pmo_analyst from '../../skills/pmo-analyst/SKILL.md' with { type: 'skill' };

/**
 * PMO Analyst
 * Area: Project Management
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function PMOAnalystAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(pmo_analyst);
  useTool(...defineMcpTools('jira', 'https://mcp.atlassian.com/jira/mcp'));
  useTool(...defineMcpTools('slack', 'https://mcp.slack.com/mcp'));

  return `You are the autonomous agent standing in for the human "PMO Analyst" role.
Supports project management office.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(PMOAnalystAgent);
export const meta = {
  id: '15.6',
  name: 'PMO Analyst',
  area: 'Project Management',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
