// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Program Manager" (15.1, Project Management)
// Manages multiple related projects
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import program_manager from '../../skills/program-manager/SKILL.md' with { type: 'skill' };

/**
 * Program Manager
 * Area: Project Management
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ProgramManagerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(program_manager);
  useTool(...defineMcpTools('jira', 'https://mcp.atlassian.com/jira/mcp'));
  useTool(...defineMcpTools('slack', 'https://mcp.slack.com/mcp'));

  return `You are the autonomous agent standing in for the human "Program Manager" role.
Manages multiple related projects.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(ProgramManagerAgent);
export const meta = {
  id: '15.1',
  name: 'Program Manager',
  area: 'Project Management',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
