// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Project Manager" (15.2, Project Management)
// Coordinates single project delivery
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import project_manager from '../../skills/project-manager/SKILL.md';

/**
 * Project Manager
 * Area: Project Management
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ProjectManagerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSkill(project_manager);
  useMcpConnection({ name: 'jira', url: 'https://mcp.atlassian.com/jira/mcp', optional: true });
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "Project Manager" role.
Coordinates single project delivery.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
ProjectManagerAgent.agentName = 'project-manager';
export const meta = {
  id: '15.2',
  name: 'Project Manager',
  area: 'Project Management',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
