// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Resource Manager" (15.5, Project Management)
// Allocates team members across projects
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import resource_manager from '../../skills/resource-manager/SKILL.md';

/**
 * Resource Manager
 * Area: Project Management
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ResourceManagerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSkill(resource_manager);
  useMcpConnection({ name: 'jira', url: 'https://mcp.atlassian.com/jira/mcp', optional: true });
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "Resource Manager" role.
Allocates team members across projects.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
ResourceManagerAgent.agentName = 'resource-manager';
export const meta = {
  id: '15.5',
  name: 'Resource Manager',
  area: 'Project Management',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
