// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Lead Business Analyst" (2.1, Business Analysis & Requirements)
// Oversees BA team and complex requirement gathering
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import lead_business_analyst from '../../skills/lead-business-analyst/SKILL.md';

/**
 * Lead Business Analyst
 * Area: Business Analysis & Requirements
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function LeadBusinessAnalystAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSkill(lead_business_analyst);
  useMcpConnection({ name: 'jira', url: 'https://mcp.atlassian.com/jira/mcp', optional: true });
  useMcpConnection({ name: 'gdrive', url: 'https://drivemcp.googleapis.com/mcp/v1', optional: true });

  return `You are the autonomous agent standing in for the human "Lead Business Analyst" role.
Oversees BA team and complex requirement gathering.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
LeadBusinessAnalystAgent.agentName = 'lead-business-analyst';
export const meta = {
  id: '2.1',
  name: 'Lead Business Analyst',
  area: 'Business Analysis & Requirements',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
