// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Process Analyst" (2.4, Business Analysis & Requirements)
// Maps and optimizes business workflows
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import process_analyst from '../../skills/process-analyst/SKILL.md';

/**
 * Process Analyst
 * Area: Business Analysis & Requirements
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ProcessAnalystAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSkill(process_analyst);
  useMcpConnection({ name: 'jira', url: 'https://mcp.atlassian.com/jira/mcp', optional: true });
  useMcpConnection({ name: 'gdrive', url: 'https://drivemcp.googleapis.com/mcp/v1', optional: true });

  return `You are the autonomous agent standing in for the human "Process Analyst" role.
Maps and optimizes business workflows.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
ProcessAnalystAgent.agentName = 'process-analyst';
export const meta = {
  id: '2.4',
  name: 'Process Analyst',
  area: 'Business Analysis & Requirements',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
