// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Requirements Engineer" (2.6, Business Analysis & Requirements)
// Formalizes and validates technical requirements
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import requirements_engineer from '../../skills/requirements-engineer/SKILL.md';

/**
 * Requirements Engineer
 * Area: Business Analysis & Requirements
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function RequirementsEngineerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSkill(requirements_engineer);
  useMcpConnection({ name: 'jira', url: 'https://mcp.atlassian.com/jira/mcp', optional: true });
  useMcpConnection({ name: 'gdrive', url: 'https://drivemcp.googleapis.com/mcp/v1', optional: true });

  return `You are the autonomous agent standing in for the human "Requirements Engineer" role.
Formalizes and validates technical requirements.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
RequirementsEngineerAgent.agentName = 'requirements-engineer';
export const meta = {
  id: '2.6',
  name: 'Requirements Engineer',
  area: 'Business Analysis & Requirements',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
