// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Requirements Engineer" (2.6, Business Analysis & Requirements)
// Formalizes and validates technical requirements
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import requirements_engineer from '../../skills/requirements-engineer/SKILL.md' with { type: 'skill' };

/**
 * Requirements Engineer
 * Area: Business Analysis & Requirements
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function RequirementsEngineerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(requirements_engineer);
  useTool(...defineMcpTools('jira', 'https://mcp.atlassian.com/jira/mcp'));
  useTool(...defineMcpTools('gdrive', 'https://drivemcp.googleapis.com/mcp/v1'));

  return `You are the autonomous agent standing in for the human "Requirements Engineer" role.
Formalizes and validates technical requirements.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(RequirementsEngineerAgent);
export const meta = {
  id: '2.6',
  name: 'Requirements Engineer',
  area: 'Business Analysis & Requirements',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
