// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Documentation Manager" (14.1, Documentation & Technical Writing)
// Oversees documentation strategy
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import documentation_manager from '../../skills/documentation-manager/SKILL.md' with { type: 'skill' };

/**
 * Documentation Manager
 * Area: Documentation & Technical Writing
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function DocumentationManagerAgent() {
  useModel('workers-ai/@cf/meta/llama-3.3-70b-instruct');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(documentation_manager);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));
  useTool(...defineMcpTools('gdrive', 'https://drivemcp.googleapis.com/mcp/v1'));

  return `You are the autonomous agent standing in for the human "Documentation Manager" role.
Oversees documentation strategy.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(DocumentationManagerAgent);
export const meta = {
  id: '14.1',
  name: 'Documentation Manager',
  area: 'Documentation & Technical Writing',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
