// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Documentation Manager" (14.1, Documentation & Technical Writing)
// Oversees documentation strategy
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import documentation_manager from '../../skills/documentation-manager/SKILL.md';

/**
 * Documentation Manager
 * Area: Documentation & Technical Writing
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function DocumentationManagerAgent() {
  useModel('cloudflare/@cf/meta/llama-3.3-70b-instruct');
  useSkill(documentation_manager);
  useMcpConnection({ name: 'github', url: 'https://mcp.github.com/mcp', optional: true });
  useMcpConnection({ name: 'gdrive', url: 'https://drivemcp.googleapis.com/mcp/v1', optional: true });

  return `You are the autonomous agent standing in for the human "Documentation Manager" role.
Oversees documentation strategy.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
DocumentationManagerAgent.agentName = 'documentation-manager';
export const meta = {
  id: '14.1',
  name: 'Documentation Manager',
  area: 'Documentation & Technical Writing',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
