// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Technical Writer" (14.2, Documentation & Technical Writing)
// Creates user guides and documentation
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import technical_writer from '../../skills/technical-writer/SKILL.md' with { type: 'skill' };

/**
 * Technical Writer
 * Area: Documentation & Technical Writing
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function TechnicalWriterAgent() {
  useModel('workers-ai/@cf/meta/llama-3.3-70b-instruct');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(technical_writer);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));
  useTool(...defineMcpTools('gdrive', 'https://drivemcp.googleapis.com/mcp/v1'));

  return `You are the autonomous agent standing in for the human "Technical Writer" role.
Creates user guides and documentation.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(TechnicalWriterAgent);
export const meta = {
  id: '14.2',
  name: 'Technical Writer',
  area: 'Documentation & Technical Writing',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
