// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Video Tutorial Creator" (14.5, Documentation & Technical Writing)
// Produces educational video content
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import video_tutorial_creator from '../../skills/video-tutorial-creator/SKILL.md' with { type: 'skill' };

/**
 * Video Tutorial Creator
 * Area: Documentation & Technical Writing
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function VideoTutorialCreatorAgent() {
  useModel('workers-ai/@cf/meta/llama-3.3-70b-instruct');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(video_tutorial_creator);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));
  useTool(...defineMcpTools('gdrive', 'https://drivemcp.googleapis.com/mcp/v1'));

  return `You are the autonomous agent standing in for the human "Video Tutorial Creator" role.
Produces educational video content.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(VideoTutorialCreatorAgent);
export const meta = {
  id: '14.5',
  name: 'Video Tutorial Creator',
  area: 'Documentation & Technical Writing',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
