// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "iOS Developer" (9.2, Mobile Development)
// Develops native iOS applications (Swift)
'use agent';

import { useModel, useSandbox, useSkill, useMcpConnection } from '@flue/runtime';
import { local } from '@flue/runtime/node';
import ios_developer from '../../skills/ios-developer/SKILL.md';

/**
 * iOS Developer
 * Area: Mobile Development
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function IOSDeveloperAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(local());
  useSkill(ios_developer);
  useMcpConnection({ name: 'github', url: 'https://mcp.github.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "iOS Developer" role.
Develops native iOS applications (Swift).
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
IOSDeveloperAgent.agentName = 'ios-developer';
export const meta = {
  id: '9.2',
  name: 'iOS Developer',
  area: 'Mobile Development',
  tier: 'container',
  confidenceThreshold: 0.7,
};
