// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "iOS Developer" (9.2, Mobile Development)
// Develops native iOS applications (Swift)
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import ios_developer from '../../skills/ios-developer/SKILL.md' with { type: 'skill' };

/**
 * iOS Developer
 * Area: Mobile Development
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function IOSDeveloperAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(ios_developer);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));

  return `You are the autonomous agent standing in for the human "iOS Developer" role.
Develops native iOS applications (Swift).
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(IOSDeveloperAgent);
export const meta = {
  id: '9.2',
  name: 'iOS Developer',
  area: 'Mobile Development',
  tier: 'container',
  confidenceThreshold: 0.7,
};
