// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Mobile DevOps Engineer" (9.7, Mobile Development)
// Manages mobile CI/CD and app store releases
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import mobile_devops_engineer from '../../skills/mobile-devops-engineer/SKILL.md' with { type: 'skill' };

/**
 * Mobile DevOps Engineer
 * Area: Mobile Development
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function MobileDevOpsEngineerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(mobile_devops_engineer);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));

  return `You are the autonomous agent standing in for the human "Mobile DevOps Engineer" role.
Manages mobile CI/CD and app store releases.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(MobileDevOpsEngineerAgent);
export const meta = {
  id: '9.7',
  name: 'Mobile DevOps Engineer',
  area: 'Mobile Development',
  tier: 'container',
  confidenceThreshold: 0.7,
};
