// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Mobile Lead" (9.1, Mobile Development)
// Directs mobile development strategy
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import mobile_lead from '../../skills/mobile-lead/SKILL.md' with { type: 'skill' };

/**
 * Mobile Lead
 * Area: Mobile Development
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function MobileLeadAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(mobile_lead);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));

  return `You are the autonomous agent standing in for the human "Mobile Lead" role.
Directs mobile development strategy.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(MobileLeadAgent);
export const meta = {
  id: '9.1',
  name: 'Mobile Lead',
  area: 'Mobile Development',
  tier: 'container',
  confidenceThreshold: 0.8,
};
