// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Mobile Lead" (9.1, Mobile Development)
// Directs mobile development strategy
'use agent';

import { useModel, useSandbox, useSkill, useMcpConnection } from '@flue/runtime';
import { local } from '@flue/runtime/node';
import mobile_lead from '../../skills/mobile-lead/SKILL.md';

/**
 * Mobile Lead
 * Area: Mobile Development
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function MobileLeadAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(local());
  useSkill(mobile_lead);
  useMcpConnection({ name: 'github', url: 'https://mcp.github.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "Mobile Lead" role.
Directs mobile development strategy.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
MobileLeadAgent.agentName = 'mobile-lead';
export const meta = {
  id: '9.1',
  name: 'Mobile Lead',
  area: 'Mobile Development',
  tier: 'container',
  confidenceThreshold: 0.8,
};
