// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Mobile UI/UX Developer" (9.6, Mobile Development)
// Specializes in mobile interface development
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import mobile_ui_ux_developer from '../../skills/mobile-ui-ux-developer/SKILL.md' with { type: 'skill' };

/**
 * Mobile UI/UX Developer
 * Area: Mobile Development
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function MobileUIUXDeveloperAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(mobile_ui_ux_developer);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));

  return `You are the autonomous agent standing in for the human "Mobile UI/UX Developer" role.
Specializes in mobile interface development.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(MobileUIUXDeveloperAgent);
export const meta = {
  id: '9.6',
  name: 'Mobile UI/UX Developer',
  area: 'Mobile Development',
  tier: 'container',
  confidenceThreshold: 0.7,
};
