// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "React Native Developer" (9.4, Mobile Development)
// Builds cross-platform apps with React Native
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import react_native_developer from '../../skills/react-native-developer/SKILL.md' with { type: 'skill' };

/**
 * React Native Developer
 * Area: Mobile Development
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ReactNativeDeveloperAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(react_native_developer);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));

  return `You are the autonomous agent standing in for the human "React Native Developer" role.
Builds cross-platform apps with React Native.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(ReactNativeDeveloperAgent);
export const meta = {
  id: '9.4',
  name: 'React Native Developer',
  area: 'Mobile Development',
  tier: 'container',
  confidenceThreshold: 0.7,
};
