// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Brand Manager" (17.8, Marketing)
// Maintains brand consistency and identity
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import brand_manager from '../../skills/brand-manager/SKILL.md';

/**
 * Brand Manager
 * Area: Marketing
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function BrandManagerAgent() {
  useModel('cloudflare/@cf/meta/llama-3.3-70b-instruct');
  useSkill(brand_manager);
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });
  useMcpConnection({ name: 'gdrive', url: 'https://drivemcp.googleapis.com/mcp/v1', optional: true });

  return `You are the autonomous agent standing in for the human "Brand Manager" role.
Maintains brand consistency and identity.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
BrandManagerAgent.agentName = 'brand-manager';
export const meta = {
  id: '17.8',
  name: 'Brand Manager',
  area: 'Marketing',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
