// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Chief Marketing Officer" (17.1, Marketing)
// Sets overall marketing strategy
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import chief_marketing_officer from '../../skills/chief-marketing-officer/SKILL.md';

/**
 * Chief Marketing Officer
 * Area: Marketing
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ChiefMarketingOfficerAgent() {
  useModel('cloudflare/@cf/meta/llama-3.3-70b-instruct');
  useSkill(chief_marketing_officer);
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });
  useMcpConnection({ name: 'gdrive', url: 'https://drivemcp.googleapis.com/mcp/v1', optional: true });

  return `You are the autonomous agent standing in for the human "Chief Marketing Officer" role.
Sets overall marketing strategy.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
ChiefMarketingOfficerAgent.agentName = 'chief-marketing-officer';
export const meta = {
  id: '17.1',
  name: 'Chief Marketing Officer',
  area: 'Marketing',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
