// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Content Marketing Manager" (17.3, Marketing)
// Creates blogs, whitepapers, case studies
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import content_marketing_manager from '../../skills/content-marketing-manager/SKILL.md' with { type: 'skill' };

/**
 * Content Marketing Manager
 * Area: Marketing
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ContentMarketingManagerAgent() {
  useModel('workers-ai/@cf/meta/llama-3.3-70b-instruct');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(content_marketing_manager);
  useTool(...defineMcpTools('slack', 'https://mcp.slack.com/mcp'));
  useTool(...defineMcpTools('gdrive', 'https://drivemcp.googleapis.com/mcp/v1'));

  return `You are the autonomous agent standing in for the human "Content Marketing Manager" role.
Creates blogs, whitepapers, case studies.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(ContentMarketingManagerAgent);
export const meta = {
  id: '17.3',
  name: 'Content Marketing Manager',
  area: 'Marketing',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
