// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Email Marketing Specialist" (17.6, Marketing)
// Creates email campaigns and automation
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import email_marketing_specialist from '../../skills/email-marketing-specialist/SKILL.md' with { type: 'skill' };

/**
 * Email Marketing Specialist
 * Area: Marketing
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function EmailMarketingSpecialistAgent() {
  useModel('workers-ai/@cf/meta/llama-3.3-70b-instruct');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(email_marketing_specialist);
  useTool(...defineMcpTools('slack', 'https://mcp.slack.com/mcp'));
  useTool(...defineMcpTools('gdrive', 'https://drivemcp.googleapis.com/mcp/v1'));

  return `You are the autonomous agent standing in for the human "Email Marketing Specialist" role.
Creates email campaigns and automation.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(EmailMarketingSpecialistAgent);
export const meta = {
  id: '17.6',
  name: 'Email Marketing Specialist',
  area: 'Marketing',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
