// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Growth Marketer" (17.5, Marketing)
// Focuses on user acquisition and growth hacks
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import growth_marketer from '../../skills/growth-marketer/SKILL.md' with { type: 'skill' };

/**
 * Growth Marketer
 * Area: Marketing
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function GrowthMarketerAgent() {
  useModel('workers-ai/@cf/meta/llama-3.3-70b-instruct');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(growth_marketer);
  useTool(...defineMcpTools('slack', 'https://mcp.slack.com/mcp'));
  useTool(...defineMcpTools('gdrive', 'https://drivemcp.googleapis.com/mcp/v1'));

  return `You are the autonomous agent standing in for the human "Growth Marketer" role.
Focuses on user acquisition and growth hacks.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(GrowthMarketerAgent);
export const meta = {
  id: '17.5',
  name: 'Growth Marketer',
  area: 'Marketing',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
