// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Marketing Analyst" (17.7, Marketing)
// Measures campaign performance and ROI
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import marketing_analyst from '../../skills/marketing-analyst/SKILL.md';

/**
 * Marketing Analyst
 * Area: Marketing
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function MarketingAnalystAgent() {
  useModel('cloudflare/@cf/meta/llama-3.3-70b-instruct');
  useSkill(marketing_analyst);
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });
  useMcpConnection({ name: 'gdrive', url: 'https://drivemcp.googleapis.com/mcp/v1', optional: true });

  return `You are the autonomous agent standing in for the human "Marketing Analyst" role.
Measures campaign performance and ROI.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
MarketingAnalystAgent.agentName = 'marketing-analyst';
export const meta = {
  id: '17.7',
  name: 'Marketing Analyst',
  area: 'Marketing',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
