// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Partner Marketing Manager" (17.10, Marketing)
// Manages co-marketing initiatives
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import partner_marketing_manager from '../../skills/partner-marketing-manager/SKILL.md';

/**
 * Partner Marketing Manager
 * Area: Marketing
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function PartnerMarketingManagerAgent() {
  useModel('cloudflare/@cf/meta/llama-3.3-70b-instruct');
  useSkill(partner_marketing_manager);
  useMcpConnection({ name: 'slack', url: 'https://mcp.slack.com/mcp', optional: true });
  useMcpConnection({ name: 'gdrive', url: 'https://drivemcp.googleapis.com/mcp/v1', optional: true });

  return `You are the autonomous agent standing in for the human "Partner Marketing Manager" role.
Manages co-marketing initiatives.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
PartnerMarketingManagerAgent.agentName = 'partner-marketing-manager';
export const meta = {
  id: '17.10',
  name: 'Partner Marketing Manager',
  area: 'Marketing',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
