// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Design System Manager" (4.7, Design)
// Maintains component libraries and design tokens
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import design_system_manager from '../../skills/design-system-manager/SKILL.md';

/**
 * Design System Manager
 * Area: Design
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function DesignSystemManagerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSkill(design_system_manager);
  useMcpConnection({ name: 'figma', url: 'https://mcp.figma.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "Design System Manager" role.
Maintains component libraries and design tokens.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
DesignSystemManagerAgent.agentName = 'design-system-manager';
export const meta = {
  id: '4.7',
  name: 'Design System Manager',
  area: 'Design',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
