// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Design Director" (4.1, Design)
// Sets design vision and standards
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { workspace } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import design_director from '../../skills/design-director/SKILL.md' with { type: 'skill' };

/**
 * Design Director
 * Area: Design
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function DesignDirectorAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(workspace({ store: 'sqlite+r2' }));
  useSkill(design_director);
  useTool(...defineMcpTools('figma', 'https://mcp.figma.com/mcp'));

  return `You are the autonomous agent standing in for the human "Design Director" role.
Sets design vision and standards.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(DesignDirectorAgent);
export const meta = {
  id: '4.1',
  name: 'Design Director',
  area: 'Design',
  tier: 'tier0',
  confidenceThreshold: 0.8,
};
