// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Interaction Designer" (4.4, Design)
// Designs interactions and microanimations
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import interaction_designer from '../../skills/interaction-designer/SKILL.md';

/**
 * Interaction Designer
 * Area: Design
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function InteractionDesignerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSkill(interaction_designer);
  useMcpConnection({ name: 'figma', url: 'https://mcp.figma.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "Interaction Designer" role.
Designs interactions and microanimations.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
InteractionDesignerAgent.agentName = 'interaction-designer';
export const meta = {
  id: '4.4',
  name: 'Interaction Designer',
  area: 'Design',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
