// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Prototyper" (4.8, Design)
// Builds interactive prototypes for testing
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import prototyper from '../../skills/prototyper/SKILL.md';

/**
 * Prototyper
 * Area: Design
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function PrototyperAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSkill(prototyper);
  useMcpConnection({ name: 'figma', url: 'https://mcp.figma.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "Prototyper" role.
Builds interactive prototypes for testing.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
PrototyperAgent.agentName = 'prototyper';
export const meta = {
  id: '4.8',
  name: 'Prototyper',
  area: 'Design',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
