// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Visual Designer" (4.5, Design)
// Creates graphics, icons, and brand elements
'use agent';

import { useModel, useSkill, useMcpConnection } from '@flue/runtime';
import visual_designer from '../../skills/visual-designer/SKILL.md';

/**
 * Visual Designer
 * Area: Design
 * Infra: Tier 0 — Workspace (SQLite + R2, no code execution)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function VisualDesignerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSkill(visual_designer);
  useMcpConnection({ name: 'figma', url: 'https://mcp.figma.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "Visual Designer" role.
Creates graphics, icons, and brand elements.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
VisualDesignerAgent.agentName = 'visual-designer';
export const meta = {
  id: '4.5',
  name: 'Visual Designer',
  area: 'Design',
  tier: 'tier0',
  confidenceThreshold: 0.7,
};
