// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Application Architect" (5.3, Software Architecture)
// Designs application structure and patterns
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { isolate } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import application_architect from '../../skills/application-architect/SKILL.md' with { type: 'skill' };

/**
 * Application Architect
 * Area: Software Architecture
 * Infra: Tier 1 — Dynamic Worker (V8 isolate, no network, fast cold start)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ApplicationArchitectAgent() {
  useModel('anthropic/claude-opus-4-6');
  useSandbox(isolate());
  useSkill(application_architect);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));
  useTool(...defineMcpTools('gdrive', 'https://drivemcp.googleapis.com/mcp/v1'));

  return `You are the autonomous agent standing in for the human "Application Architect" role.
Designs application structure and patterns.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(ApplicationArchitectAgent);
export const meta = {
  id: '5.3',
  name: 'Application Architect',
  area: 'Software Architecture',
  tier: 'tier1',
  confidenceThreshold: 0.7,
};
