// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Chief Architect" (5.1, Software Architecture)
// Defines enterprise architecture standards
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { isolate } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import chief_architect from '../../skills/chief-architect/SKILL.md' with { type: 'skill' };

/**
 * Chief Architect
 * Area: Software Architecture
 * Infra: Tier 1 — Dynamic Worker (V8 isolate, no network, fast cold start)
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function ChiefArchitectAgent() {
  useModel('anthropic/claude-opus-4-6');
  useSandbox(isolate());
  useSkill(chief_architect);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));
  useTool(...defineMcpTools('gdrive', 'https://drivemcp.googleapis.com/mcp/v1'));

  return `You are the autonomous agent standing in for the human "Chief Architect" role.
Defines enterprise architecture standards.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(ChiefArchitectAgent);
export const meta = {
  id: '5.1',
  name: 'Chief Architect',
  area: 'Software Architecture',
  tier: 'tier1',
  confidenceThreshold: 0.8,
};
