// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Integration Architect" (5.6, Software Architecture)
// Designs API and system integration strategies
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { isolate } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import integration_architect from '../../skills/integration-architect/SKILL.md' with { type: 'skill' };

/**
 * Integration Architect
 * Area: Software Architecture
 * Infra: Tier 1 — Dynamic Worker (V8 isolate, no network, fast cold start)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function IntegrationArchitectAgent() {
  useModel('anthropic/claude-opus-4-6');
  useSandbox(isolate());
  useSkill(integration_architect);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));
  useTool(...defineMcpTools('gdrive', 'https://drivemcp.googleapis.com/mcp/v1'));

  return `You are the autonomous agent standing in for the human "Integration Architect" role.
Designs API and system integration strategies.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(IntegrationArchitectAgent);
export const meta = {
  id: '5.6',
  name: 'Integration Architect',
  area: 'Software Architecture',
  tier: 'tier1',
  confidenceThreshold: 0.7,
};
