// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Solutions Architect" (5.2, Software Architecture)
// Designs end-to-end solution architecture
'use agent';

import { useModel, useSandbox, useSkill, useMcpConnection } from '@flue/runtime';
import { local } from '@flue/runtime/node';
import solutions_architect from '../../skills/solutions-architect/SKILL.md';

/**
 * Solutions Architect
 * Area: Software Architecture
 * Infra: Tier 1 — Dynamic Worker (V8 isolate, no network, fast cold start)
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function SolutionsArchitectAgent() {
  useModel('anthropic/claude-opus-4-6');
  useSandbox(local());
  useSkill(solutions_architect);
  useMcpConnection({ name: 'github', url: 'https://mcp.github.com/mcp', optional: true });
  useMcpConnection({ name: 'gdrive', url: 'https://drivemcp.googleapis.com/mcp/v1', optional: true });

  return `You are the autonomous agent standing in for the human "Solutions Architect" role.
Designs end-to-end solution architecture.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
SolutionsArchitectAgent.agentName = 'solutions-architect';
export const meta = {
  id: '5.2',
  name: 'Solutions Architect',
  area: 'Software Architecture',
  tier: 'tier1',
  confidenceThreshold: 0.7,
};
