// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Full Stack Lead" (8.1, Full Stack Development)
// Manages cross-stack development efforts
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import full_stack_lead from '../../skills/full-stack-lead/SKILL.md' with { type: 'skill' };

/**
 * Full Stack Lead
 * Area: Full Stack Development
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function FullStackLeadAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(full_stack_lead);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));
  useTool(...defineMcpTools('figma', 'https://mcp.figma.com/mcp'));

  return `You are the autonomous agent standing in for the human "Full Stack Lead" role.
Manages cross-stack development efforts.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(FullStackLeadAgent);
export const meta = {
  id: '8.1',
  name: 'Full Stack Lead',
  area: 'Full Stack Development',
  tier: 'container',
  confidenceThreshold: 0.8,
};
