// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "MEAN/MERN Stack Developer" (8.3, Full Stack Development)
// Specializes in JavaScript full stack
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import mean_mern_stack_developer from '../../skills/mean-mern-stack-developer/SKILL.md' with { type: 'skill' };

/**
 * MEAN/MERN Stack Developer
 * Area: Full Stack Development
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function MEANMERNStackDeveloperAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(mean_mern_stack_developer);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));
  useTool(...defineMcpTools('figma', 'https://mcp.figma.com/mcp'));

  return `You are the autonomous agent standing in for the human "MEAN/MERN Stack Developer" role.
Specializes in JavaScript full stack.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(MEANMERNStackDeveloperAgent);
export const meta = {
  id: '8.3',
  name: 'MEAN/MERN Stack Developer',
  area: 'Full Stack Development',
  tier: 'container',
  confidenceThreshold: 0.7,
};
