// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Rapid Prototyper" (8.4, Full Stack Development)
// Quickly builds MVPs and proofs of concept
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import rapid_prototyper from '../../skills/rapid-prototyper/SKILL.md' with { type: 'skill' };

/**
 * Rapid Prototyper
 * Area: Full Stack Development
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function RapidPrototyperAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(rapid_prototyper);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));
  useTool(...defineMcpTools('figma', 'https://mcp.figma.com/mcp'));

  return `You are the autonomous agent standing in for the human "Rapid Prototyper" role.
Quickly builds MVPs and proofs of concept.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(RapidPrototyperAgent);
export const meta = {
  id: '8.4',
  name: 'Rapid Prototyper',
  area: 'Full Stack Development',
  tier: 'container',
  confidenceThreshold: 0.7,
};
