// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "API Developer" (7.3, Backend Development)
// Designs and implements REST/GraphQL APIs
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import api_developer from '../../skills/api-developer/SKILL.md' with { type: 'skill' };

/**
 * API Developer
 * Area: Backend Development
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function APIDeveloperAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(api_developer);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));

  return `You are the autonomous agent standing in for the human "API Developer" role.
Designs and implements REST/GraphQL APIs.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(APIDeveloperAgent);
export const meta = {
  id: '7.3',
  name: 'API Developer',
  area: 'Backend Development',
  tier: 'container',
  confidenceThreshold: 0.7,
};
