// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Backend Developer" (7.2, Backend Development)
// Builds APIs, business logic, and services
'use agent';

import { useModel, useSandbox, useSkill, useMcpConnection } from '@flue/runtime';
import { local } from '@flue/runtime/node';
import backend_developer from '../../skills/backend-developer/SKILL.md';

/**
 * Backend Developer
 * Area: Backend Development
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function BackendDeveloperAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(local());
  useSkill(backend_developer);
  useMcpConnection({ name: 'github', url: 'https://mcp.github.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "Backend Developer" role.
Builds APIs, business logic, and services.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
BackendDeveloperAgent.agentName = 'backend-developer';
export const meta = {
  id: '7.2',
  name: 'Backend Developer',
  area: 'Backend Development',
  tier: 'container',
  confidenceThreshold: 0.7,
};
