// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Backend Lead/Principal" (7.1, Backend Development)
// Leads backend team and architecture
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import backend_lead_principal from '../../skills/backend-lead-principal/SKILL.md' with { type: 'skill' };

/**
 * Backend Lead/Principal
 * Area: Backend Development
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.8 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function BackendLeadPrincipalAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(backend_lead_principal);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));

  return `You are the autonomous agent standing in for the human "Backend Lead/Principal" role.
Leads backend team and architecture.
Confidence threshold for self-approval: 0.8.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(BackendLeadPrincipalAgent);
export const meta = {
  id: '7.1',
  name: 'Backend Lead/Principal',
  area: 'Backend Development',
  tier: 'container',
  confidenceThreshold: 0.8,
};
