// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Backend Performance Engineer" (7.6, Backend Development)
// Optimizes server performance and scalability
'use agent';

import { useModel, useSandbox, useSkill, useMcpConnection } from '@flue/runtime';
import { local } from '@flue/runtime/node';
import backend_performance_engineer from '../../skills/backend-performance-engineer/SKILL.md';

/**
 * Backend Performance Engineer
 * Area: Backend Development
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function BackendPerformanceEngineerAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(local());
  useSkill(backend_performance_engineer);
  useMcpConnection({ name: 'github', url: 'https://mcp.github.com/mcp', optional: true });

  return `You are the autonomous agent standing in for the human "Backend Performance Engineer" role.
Optimizes server performance and scalability.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

// Pinned durable identity: renaming the function later won't orphan the
// conversation storage keyed by agent name. The meta export is this
// repo's own bridge convention (consumed by scripts/run-agent.mjs),
// not Flue API.
BackendPerformanceEngineerAgent.agentName = 'backend-performance-engineer';
export const meta = {
  id: '7.6',
  name: 'Backend Performance Engineer',
  area: 'Backend Development',
  tier: 'container',
  confidenceThreshold: 0.7,
};
