// AUTO-GENERATED by scripts/generate-agents.mjs — do not hand-edit.
// Human role twin: "Integration Developer" (7.7, Backend Development)
// Builds connections to external systems
'use agent';

import { useModel, useSandbox, useSkill, useTool, createAgent } from '@flue/runtime';
import { container } from '@flue/runtime/cloudflare';
import { defineMcpTools } from '@flue/runtime/mcp';
import integration_developer from '../../skills/integration-developer/SKILL.md' with { type: 'skill' };

/**
 * Integration Developer
 * Area: Backend Development
 * Infra: Escalates Tier 1 → Cloudflare Container/Sandbox for full toolchain execution
 * Escalation: confidence < 0.7 or a governance trigger fires
 *             → Workflow sleeps and routes to the human owner of this function.
 */
export function IntegrationDeveloperAgent() {
  useModel('anthropic/claude-sonnet-4-6');
  useSandbox(container({ ephemeral: true }));
  useSkill(integration_developer);
  useTool(...defineMcpTools('github', 'https://mcp.github.com/mcp'));

  return `You are the autonomous agent standing in for the human "Integration Developer" role.
Builds connections to external systems.
Confidence threshold for self-approval: 0.7.
Below that threshold, or if a fixed governance trigger fires (legal, >$10k
budget, production incident, customer-facing comms, major architecture
change), pause and escalate to the human owner rather than proceeding.`;
}

export const agent = createAgent(IntegrationDeveloperAgent);
export const meta = {
  id: '7.7',
  name: 'Integration Developer',
  area: 'Backend Development',
  tier: 'container',
  confidenceThreshold: 0.7,
};
